/**
*   @file    Can_Cfg.h
*   @version 1.0.1
*
*   @brief   AUTOSAR Can - module interface
*   @details Configuration settings generated by user settings.
*
*   @addtogroup CAN_DRIVER
*   @{
*/
/*==================================================================================================
*   Project              : AUTOSAR 4.0 MCAL
*   Platform             : PA
*   Peripheral           : FLEXCAN
*   Dependencies         : 
*
*   Autosar Version      : 4.0.3
*   Autosar Revision     : ASR_REL_4_0_REV_0003
*   Autosar Conf.Variant :
*   SW Version           : 1.0.1
*   Build Version        : MPC560xB_MCAL_1_0_1_RTM_ASR_REL_4_0_REV_0003_20140606
*
*   (c) Copyright 2006-2014 Freescale Semiconductor Inc and STMicroelectronics
*   All Rights Reserved.
==================================================================================================*/
/*==================================================================================================
==================================================================================================*/
/*
@brief   (CAN023) The consistency of the configuration must be checked by the configuration tool(s).
@brief   (CAN022) The code configurator of the Can module is CAN controller specific.
         If the CAN controller is sited on-chip, the code generation tool for the Can module is Controller specific.
         If the CAN controller is an external device the generation tool must not be Controller specific.
@brief   (CAN024) The valid values that can be configured are hardware dependent.
         Therefore the rules and constraints can't be given in the standard.
         The configuration tool is responsible to do a static configuration checking, also regarding dependencies between modules (i.e. Port driver, MCU driver etc.)
*/
/*
* @file    Can_Cfg.h
* @implements DCAN02001, DCAN02606, DCAN02603
*/

#ifndef CAN_CFG_H
#define CAN_CFG_H

#ifdef __cplusplus
extern "C"{
#endif

/**
* @page misra_violations MISRA-C:2004 violations
*
* @section Can_Cfg_h_REF_1
* Violates MISRA 2004 Required Rule 19.15, Repeated include file MemMap.h
* There are different kinds of execution code sections.
*
* @section Can_Cfg_h_REF_2
* Violates MISRA 2004 Advisory Rule 19.7, Function-like macro defined.
* This violation is because many controllers have defined Interrupt handlers with only 1 macro.
*
* @section Can_Cfg_h_REF_3
* Violates MISRA 2004 Required Rule 1.4, Identifier clash, Identifier clash
* This violation is due to the requirement that request to have a file version check.
*
* @section Can_Cfg_h_REF_4
* Violates MISRA 2004 Required Rule 19.4, C macros shall only expand to a braced initialiser, a constant, a
* parenthesised expression, a type qualifier, a storage class specifier, or a do-while-zero construct
*
* @section Can_Cfg_h_REF_5
* Violates MISRA 2004 Required Rule 5.1, Identifiers (internal and external) shall not rely on the
* significance of more than 31 characters.
*
* @section Can_Cfg_h_REF_6
* Violates MISRA 2004 Required Rule 19.4, C macros shall only expand to a braced initialiser, a constant, a
* parenthesised expression, a type qualifier, a storage class specifier, or a do-while-zero construct
*
* @section Can_Cfg_h_REF_7
* Violates MISRA 2004 Required Rule 5.1, Identifiers (internal and external) shall not rely on the
* significance of more than 31 characters.
*/
/*==================================================================================================
*                                        INCLUDE FILES
* 1) system and project includes
* 2) needed interfaces from external units
* 3) internal and external interfaces from this unit
==================================================================================================*/
/* @violates @ref Can_Cfg_h_REF_1 Violates MISRA 2004 Required Rule 19.15, Repeated include file MemMap.h*/
#include "Std_Types.h"
#include "Soc_Ips.h"
#include "Mcal.h"

/*==================================================================================================
*                              SOURCE FILE VERSION INFORMATION
==================================================================================================*/
/*
* @file           Can_Cfg.h
* @implements     DCAN02604
*/
#define CAN_VENDOR_ID_CFG                       43
#define CAN_MODULE_ID_CFG                       80
/* @violates @ref Can_Cfg_h_REF_5 This is required as per autosar Requirement. */
#define CAN_AR_RELEASE_MAJOR_VERSION_CFG_H      4
/* @violates @ref Can_Cfg_h_REF_5 This is required as per autosar Requirement. */
#define CAN_AR_RELEASE_MINOR_VERSION_CFG_H      0
/* @violates @ref Can_Cfg_h_REF_5 This is required as per autosar Requirement. */
#define CAN_AR_RELEASE_REVISION_VERSION_CFG_H   3
#define CAN_SW_MAJOR_VERSION_CFG_H              1
#define CAN_SW_MINOR_VERSION_CFG_H              0
#define CAN_SW_PATCH_VERSION_CFG_H              1


[!NOCODE!]
[!/* Check if the number of Controllers is the same in all Config Sets */!]
[!VAR "z"="0"!]
[!VAR "x"="num:i(count(CanConfigSet/*[1]/CanController/*))"!]
[!LOOP "CanConfigSet/*"!]
    [!VAR "y"="num:i(count(node:current()/CanController/*))"!]
    [!IF "($y = $x)"!]
        [!VAR "z"="@name"!]
    [!ELSE!]
        [!ERROR!] Number of CanControllers (=[!"$y"!]) in [!"@name"!] is different from Number of CanControllers [!"$x"!] in (= [!"$z"!]).[!ENDERROR!]
    [!ENDIF!]
[!ENDLOOP!]

[!/* Check if the settings for Rx/Tx/BusOff/WakeUp processing is the same for all Config sets (because are pre-compile parameters) */!]
[!VAR "cs"="num:i(count(CanConfigSet/*))"!]
[!IF "$cs>1"!]
    [!VAR "rxproc_a"="0"!][!VAR "txproc_a"="0"!][!VAR "boproc_a"="0"!][!VAR "wuproc_a"="0"!]
    [!VAR "rxproc_b"="0"!][!VAR "txproc_b"="0"!][!VAR "boproc_b"="0"!][!VAR "wuproc_b"="0"!]
    [!VAR "rxproc_c"="0"!][!VAR "txproc_c"="0"!][!VAR "boproc_c"="0"!][!VAR "wuproc_c"="0"!]
    [!VAR "rxproc_d"="0"!][!VAR "txproc_d"="0"!][!VAR "boproc_d"="0"!][!VAR "wuproc_d"="0"!]
    [!VAR "rxproc_e"="0"!][!VAR "txproc_e"="0"!][!VAR "boproc_e"="0"!][!VAR "wuproc_e"="0"!]
    [!VAR "rxproc_f"="0"!][!VAR "txproc_f"="0"!][!VAR "boproc_f"="0"!][!VAR "wuproc_f"="0"!]
    [!/* Get the values from First ConfigSet of these pre-compile parameters */!]
    [!LOOP "CanConfigSet/*[1]/CanController/*"!]
        [!IF "CanHwChannel='FlexCAN_A'"!]
            [!VAR "rxproc_a"="CanRxProcessing"!]
            [!VAR "txproc_a"="CanTxProcessing"!]
            [!VAR "boproc_a"="CanBusoffProcessing"!]
            [!IF "CanWakeupSupport = 'true'"!]
                [!VAR "wuproc_a"="CanWakeupProcessing"!]
            [!ENDIF!]
        [!ELSEIF "CanHwChannel='FlexCAN_B'"!]
            [!VAR "rxproc_b"="CanRxProcessing"!]
            [!VAR "txproc_b"="CanTxProcessing"!]
            [!VAR "boproc_b"="CanBusoffProcessing"!]
            [!IF "CanWakeupSupport = 'true'"!]
                [!VAR "wuproc_b"="CanWakeupProcessing"!]
            [!ENDIF!]
         [!ELSEIF "CanHwChannel='FlexCAN_C'"!]
            [!VAR "rxproc_c"="CanRxProcessing"!]
            [!VAR "txproc_c"="CanTxProcessing"!]
            [!VAR "boproc_c"="CanBusoffProcessing"!]
            [!IF "CanWakeupSupport = 'true'"!]
                [!VAR "wuproc_c"="CanWakeupProcessing"!]
            [!ENDIF!]
         [!ELSEIF "CanHwChannel='FlexCAN_D'"!]
            [!VAR "rxproc_d"="CanRxProcessing"!]
            [!VAR "txproc_d"="CanTxProcessing"!]
            [!VAR "boproc_d"="CanBusoffProcessing"!]
            [!IF "CanWakeupSupport = 'true'"!]
                [!VAR "wuproc_d"="CanWakeupProcessing"!]
            [!ENDIF!]
         [!ELSEIF "CanHwChannel='FlexCAN_E'"!]
            [!VAR "rxproc_e"="CanRxProcessing"!]
            [!VAR "txproc_e"="CanTxProcessing"!]
            [!VAR "boproc_e"="CanBusoffProcessing"!]
            [!IF "CanWakeupSupport = 'true'"!]
                [!VAR "wuproc_e"="CanWakeupProcessing"!]
            [!ENDIF!]
          [!ELSEIF "CanHwChannel='FlexCAN_F'"!]
            [!VAR "rxproc_f"="CanRxProcessing"!]
            [!VAR "txproc_f"="CanTxProcessing"!]
            [!VAR "boproc_f"="CanBusoffProcessing"!]
            [!IF "CanWakeupSupport = 'true'"!]
                [!VAR "wuproc_f"="CanWakeupProcessing"!]
              [!ENDIF!]
          [!ELSEIF "CanHwChannel='FlexCAN_G'"!]
            [!VAR "rxproc_g"="CanRxProcessing"!]
            [!VAR "txproc_g"="CanTxProcessing"!]
            [!VAR "boproc_g"="CanBusoffProcessing"!]
            [!IF "CanWakeupSupport = 'true'"!]
                [!VAR "wuproc_g"="CanWakeupProcessing"!]
              [!ENDIF!]
          [!ELSEIF "CanHwChannel='FlexCAN_H'"!]
            [!VAR "rxproc_h"="CanRxProcessing"!]
            [!VAR "txproc_h"="CanTxProcessing"!]
            [!VAR "boproc_h"="CanBusoffProcessing"!]
            [!IF "CanWakeupSupport = 'true'"!]
                [!VAR "wuproc_h"="CanWakeupProcessing"!]
              [!ENDIF!]
        [!ENDIF!]
    [!ENDLOOP!]
    [!VAR "rx_a"="0"!][!VAR "tx_a"="0"!][!VAR "bo_a"="0"!][!VAR "wu_a"="0"!]
    [!VAR "rx_b"="0"!][!VAR "tx_b"="0"!][!VAR "bo_b"="0"!][!VAR "wu_b"="0"!]
    [!VAR "rx_c"="0"!][!VAR "tx_c"="0"!][!VAR "bo_c"="0"!][!VAR "wu_c"="0"!]
    [!VAR "rx_d"="0"!][!VAR "tx_d"="0"!][!VAR "bo_d"="0"!][!VAR "wu_d"="0"!]
    [!VAR "rx_e"="0"!][!VAR "tx_e"="0"!][!VAR "bo_e"="0"!][!VAR "wu_e"="0"!]
    [!VAR "rx_f"="0"!][!VAR "tx_f"="0"!][!VAR "bo_f"="0"!][!VAR "wu_f"="0"!]
    [!/* Processing modes are Pre-compile parameters -> MUST have the same values in all CanConfigSet's  */!]
    [!LOOP "CanConfigSet/*"!]
        [!LOOP "CanController/*"!]
            [!IF "CanHwChannel='FlexCAN_A'"!]
                [!VAR "rx_a"="CanRxProcessing"!]
                [!IF "($rxproc_a!=$rx_a)"!]
                    [!ERROR!] CanRxProcessing must have the same values for Can_A in all CanConfigSets because are Pre-Compile Parameters.[!ENDERROR!]
                [!ENDIF!]
                [!VAR "tx_a"="CanTxProcessing"!]
                [!IF "($txproc_a!=$tx_a)"!]
                    [!ERROR!] CanTxProcessing must have the same values for Can_A in all CanConfigSets because are Pre-Compile Parameters.[!ENDERROR!]
                [!ENDIF!]
                [!VAR "bo_a"="CanBusoffProcessing"!]
                [!IF "($boproc_a!=$bo_a)"!]
                    [!ERROR!] CanBusoffProcessing must have the same values for Can_A in all CanConfigSets because are Pre-Compile Parameters.[!ENDERROR!]
                [!ENDIF!]
                [!IF "CanWakeupSupport = 'true'"!]
                    [!VAR "wu_a"="CanWakeupProcessing"!]
                    [!IF "($wuproc_a!=$wu_a)"!]
                        [!ERROR!] CanWakeupProcessing must have the same values for Can_A in all CanConfigSets because are Pre-Compile Parameters.[!ENDERROR!]
                    [!ENDIF!]
                [!ENDIF!]
            [!ELSEIF "CanHwChannel = 'FlexCAN_B'"!]
                [!VAR "rx_b"="CanRxProcessing"!]
                [!IF "($rxproc_b!=$rx_b)"!]
                    [!ERROR!] CanRxProcessing must have the same values for Can_B in all CanConfigSets because are Pre-Compile Parameters.[!ENDERROR!]
                [!ENDIF!]
                [!VAR "tx_b"="CanTxProcessing"!]
                [!IF "($txproc_b!=$tx_b)"!]
                    [!ERROR!] CanTxProcessing must have the same values for Can_B in all CanConfigSets because are Pre-Compile Parameters.[!ENDERROR!]
                [!ENDIF!]
                [!VAR "bo_b"="CanBusoffProcessing"!]
                [!IF "($boproc_b!=$bo_b)"!]
                    [!ERROR!] CanBusoffProcessing must have the same values for Can_B in all CanConfigSets because are Pre-Compile Parameters.[!ENDERROR!]
                [!ENDIF!]
                [!IF "CanWakeupSupport = 'true'"!]
                    [!VAR "wu_b"="CanWakeupProcessing"!]
                    [!IF "($wuproc_b!=$wu_b)"!]
                        [!ERROR!] CanWakeupProcessing must have the same values for Can_B in all CanConfigSets because are Pre-Compile Parameters.[!ENDERROR!]
                    [!ENDIF!]
                [!ENDIF!]
            [!ELSEIF "CanHwChannel = 'FlexCAN_C'"!]
                [!VAR "rx_c"="CanRxProcessing"!]
                [!IF "($rxproc_c!=$rx_c)"!]
                    [!ERROR!] CanRxProcessing must have the same values for Can_C in all CanConfigSets because are Pre-Compile Parameters.[!ENDERROR!]
                [!ENDIF!]
                [!VAR "tx_c"="CanTxProcessing"!]
                [!IF "($txproc_c!=$tx_c)"!]
                    [!ERROR!] CanTxProcessing must have the same values for Can_C in all CanConfigSets because are Pre-Compile Parameters.[!ENDERROR!]
                [!ENDIF!]
                [!VAR "bo_c"="CanBusoffProcessing"!]
                [!IF "($boproc_c!=$bo_c)"!]
                    [!ERROR!] CanBusoffProcessing must have the same values for Can_C in all CanConfigSets because are Pre-Compile Parameters.[!ENDERROR!]
                [!ENDIF!]
                [!IF "CanWakeupSupport = 'true'"!]
                    [!VAR "wu_c"="CanWakeupProcessing"!]
                    [!IF "($wuproc_c!=$wu_c)"!]
                        [!ERROR!] CanWakeupProcessing must have the same values for Can_C in all CanConfigSets because are Pre-Compile Parameters.[!ENDERROR!]
                    [!ENDIF!]
                [!ENDIF!]
            [!ELSEIF "CanHwChannel = 'FlexCAN_D'"!]
                [!VAR "rx_d"="CanRxProcessing"!]
                [!IF "($rxproc_d!=$rx_d)"!]
                    [!ERROR!] CanRxProcessing must have the same values for Can_D in all CanConfigSets because are Pre-Compile Parameters.[!ENDERROR!]
                [!ENDIF!]
                [!VAR "tx_d"="CanTxProcessing"!]
                [!IF "($txproc_d!=$tx_d)"!]
                    [!ERROR!] CanTxProcessing must have the same values for Can_D in all CanConfigSets because are Pre-Compile Parameters.[!ENDERROR!]
                [!ENDIF!]
                [!VAR "bo_d"="CanBusoffProcessing"!]
                [!IF "($boproc_d!=$bo_d)"!]
                    [!ERROR!] CanBusoffProcessing must have the same values for Can_D in all CanConfigSets because are Pre-Compile Parameters.[!ENDERROR!]
                [!ENDIF!]
                [!IF "CanWakeupSupport = 'true'"!]
                    [!VAR "wu_d"="CanWakeupProcessing"!]
                    [!IF "($wuproc_d!=$wu_d)"!]
                        [!ERROR!] CanWakeupProcessing must have the same values for Can_D in all CanConfigSets because are Pre-Compile Parameters.[!ENDERROR!]
                    [!ENDIF!]
                [!ENDIF!]
            [!ELSEIF "CanHwChannel = 'FlexCAN_E'"!]
                [!VAR "rx_e"="CanRxProcessing"!]
                [!IF "($rxproc_e!=$rx_e)"!]
                    [!ERROR!] CanRxProcessing must have the same values for Can_E in all CanConfigSets because are Pre-Compile Parameters.[!ENDERROR!]
                [!ENDIF!]
                [!VAR "tx_e"="CanTxProcessing"!]
                [!IF "($txproc_e!=$tx_e)"!]
                    [!ERROR!] CanTxProcessing must have the same values for Can_E in all CanConfigSets because are Pre-Compile Parameters.[!ENDERROR!]
                [!ENDIF!]
                [!VAR "bo_e"="CanBusoffProcessing"!]
                [!IF "($boproc_e!=$bo_e)"!]
                    [!ERROR!] CanBusoffProcessing must have the same values for Can_E in all CanConfigSets because are Pre-Compile Parameters.[!ENDERROR!]
                [!ENDIF!]
                [!IF "CanWakeupSupport = 'true'"!]
                    [!VAR "wu_e"="CanWakeupProcessing"!]
                    [!IF "($wuproc_e!=$wu_e)"!]
                        [!ERROR!] CanWakeupProcessing must have the same values for Can_E in all CanConfigSets because are Pre-Compile Parameters.[!ENDERROR!]
                    [!ENDIF!]
                [!ENDIF!]
            [!ELSEIF "CanHwChannel = 'FlexCAN_F'"!]
                [!VAR "rx_f"="CanRxProcessing"!]
                [!IF "($rxproc_f!=$rx_f)"!]
                    [!ERROR!] CanRxProcessing must have the same values for Can_F in all CanConfigSets because are Pre-Compile Parameters.[!ENDERROR!]
                [!ENDIF!]
                [!VAR "tx_f"="CanTxProcessing"!]
                [!IF "($txproc_f!=$tx_f)"!]
                    [!ERROR!] CanTxProcessing must have the same values for Can_F in all CanConfigSets because are Pre-Compile Parameters.[!ENDERROR!]
                [!ENDIF!]
                [!VAR "bo_f"="CanBusoffProcessing"!]
                [!IF "($boproc_f!=$bo_f)"!]
                    [!ERROR!] CanBusoffProcessing must have the same values for Can_F in all CanConfigSets because are Pre-Compile Parameters.[!ENDERROR!]
                [!ENDIF!]
                [!IF "CanWakeupSupport = 'true'"!]
                    [!VAR "wu_f"="CanWakeupProcessing"!]
                    [!IF "($wuproc_f!=$wu_f)"!]
                        [!ERROR!] CanWakeupProcessing must have the same values for Can_F in all CanConfigSets because are Pre-Compile Parameters.[!ENDERROR!]
                    [!ENDIF!]
                [!ENDIF!]
            [!ELSEIF "CanHwChannel = 'FlexCAN_G'"!]
                [!VAR "rx_g"="CanRxProcessing"!]
                [!IF "($rxproc_g!=$rx_g)"!]
                    [!ERROR!] CanRxProcessing must have the same values for Can_G in all CanConfigSets because are Pre-Compile Parameters.[!ENDERROR!]
                [!ENDIF!]
                [!VAR "tx_g"="CanTxProcessing"!]
                [!IF "($txproc_g!=$tx_g)"!]
                    [!ERROR!] CanTxProcessing must have the same values for Can_G in all CanConfigSets because are Pre-Compile Parameters.[!ENDERROR!]
                [!ENDIF!]
                [!VAR "bo_g"="CanBusoffProcessing"!]
                [!IF "($boproc_g!=$bo_g)"!]
                    [!ERROR!] CanBusoffProcessing must have the same values for Can_G in all CanConfigSets because are Pre-Compile Parameters.[!ENDERROR!]
                [!ENDIF!]
                [!IF "CanWakeupSupport = 'true'"!]
                    [!VAR "wu_g"="CanWakeupProcessing"!]
                    [!IF "($wuproc_g!=$wu_g)"!]
                        [!ERROR!] CanWakeupProcessing must have the same values for Can_G in all CanConfigSets because are Pre-Compile Parameters.[!ENDERROR!]
                    [!ENDIF!]
                [!ENDIF!]
            [!ELSEIF "CanHwChannel = 'FlexCAN_H'"!]
                [!VAR "rx_h"="CanRxProcessing"!]
                [!IF "($rxproc_h!=$rx_h)"!]
                    [!ERROR!] CanRxProcessing must have the same values for Can_H in all CanConfigSets because are Pre-Compile Parameters.[!ENDERROR!]
                [!ENDIF!]
                [!VAR "tx_h"="CanTxProcessing"!]
                [!IF "($txproc_h!=$tx_h)"!]
                    [!ERROR!] CanTxProcessing must have the same values for Can_H in all CanConfigSets because are Pre-Compile Parameters.[!ENDERROR!]
                [!ENDIF!]
                [!VAR "bo_h"="CanBusoffProcessing"!]
                [!IF "($boproc_h!=$bo_h)"!]
                    [!ERROR!] CanBusoffProcessing must have the same values for Can_H in all CanConfigSets because are Pre-Compile Parameters.[!ENDERROR!]
                [!ENDIF!]
                [!IF "CanWakeupSupport = 'true'"!]
                    [!VAR "wu_h"="CanWakeupProcessing"!]
                    [!IF "($wuproc_h!=$wu_h)"!]
                        [!ERROR!] CanWakeupProcessing must have the same values for Can_H in all CanConfigSets because are Pre-Compile Parameters.[!ENDERROR!]
                    [!ENDIF!]
                [!ENDIF!]
            [!ENDIF!]
        [!ENDLOOP!]
    [!ENDLOOP!]
[!ENDIF!]

[!ENDNOCODE!]

/*==================================================================================================
*                                          CONSTANTS
==================================================================================================*/
/**
* @brief          Implicit index value used by Full can hardware objects.
* @details        Implicit index value used by Full can hardware objects.
*/
#define CAN_MAXMASKCOUNT    65535U
/**
* @brief          Can Controllers. Defines for conversion between object names and object IDs.
* @details        Can Controllers. Defines for conversion between object names and object IDs.
                  (PR-MCAL-2944)Numeric ID's in configuration and definition of symbolic names in Can_Cfg.h file
*
* @implements     DCAN02607
*/[!NOCODE!]
[!/* Check if two controllers have the same name in any ConfigSet */!]
[!VAR "OuterLoopCounter" = "0"!][!VAR "InnerLoopCounter" = "0"!]
[!LOOP "CanConfigSet/*/CanController/*"!]
    [!VAR "OuterLoopCounter" = "$OuterLoopCounter + 1"!]
    [!VAR "InnerLoopCounter" = "0"!]
    [!VAR "Matchcounter" = "0"!]
    [!VAR "Name" = "node:name(.)"!]
    [!LOOP "../../../*/CanController/*"!]
        [!VAR "InnerLoopCounter" = "$InnerLoopCounter + 1"!]
        [!IF "$OuterLoopCounter >= $InnerLoopCounter"!]
            [!IF "($Name = node:name(.))"!]
                [!VAR "Matchcounter" = "$Matchcounter + 1"!]
            [!ENDIF!]
        [!ENDIF!]
    [!ENDLOOP!]
    [!IF "$Matchcounter = 1"!]
        [!CODE!]
/* @violates @ref Can_Cfg_h_REF_5 This is required as per autosar Requirement. */
/* @violates @ref Can_Cfg_h_REF_3 Violates MISRA 2004 Required Rule 1.4, Identifier clash */
#define CanConf_CanController_[!"@name"!] ((uint8)[!"CanControllerId"!]U)  /* Default configuration for [!"CanHwChannel"!] */
        [!ENDCODE!]
    [!ENDIF!]
[!ENDLOOP!]
[!ENDNOCODE!]

/**
* @brief          Can Controller Configurations.
* @details        Can Controller Configurations.
                  (PR-MCAL-2944)Numeric ID's in configuration and definition of symbolic names in Can_Cfg.h file.
*
* @implements     DCAN02608
*/[!NOCODE!]
[!VAR "OuterLoopCounter" = "0"!][!VAR "InnerLoopCounter" = "0"!]
[!LOOP "CanConfigSet/*/CanController/*"!]
    [!VAR "OuterLoopCounter" = "$OuterLoopCounter + 1"!]
    [!VAR "InnerLoopCounter" = "0"!]
    [!VAR "Matchcounter" = "0"!]
    [!VAR "Name" = "node:name(.)"!]
    [!LOOP "../../../*/CanController/*"!]
        [!VAR "InnerLoopCounter" = "$InnerLoopCounter + 1"!]
        [!IF "$OuterLoopCounter >= $InnerLoopCounter"!]
            [!IF "($Name = node:name(.))"!]
                [!VAR "Matchcounter" = "$Matchcounter + 1"!]
            [!ENDIF!]
        [!ENDIF!]
    [!ENDLOOP!]
    [!IF "$Matchcounter = 1"!]
        [!CODE!]
#define [!"@name"!]_config ([!"@index"!]U)  /* Default configuration for CanController ID=[!"num:i(CanControllerId)"!], [!"CanHwChannel"!] */
        [!ENDCODE!]
    [!ENDIF!]
[!ENDLOOP!]
[!ENDNOCODE!]

/**
* @brief          Can Hardware Objects.
* @details        Can Hardware Objects.
                  (PR-MCAL-2944)Numeric ID's in configuration and definition of symbolic names in Can_Cfg.h file.
*
* @implements     DCAN02609
*/[!NOCODE!]
[!VAR "OuterLoopCounter" = "0"!][!VAR "InnerLoopCounter" = "0"!]
[!LOOP "CanConfigSet/*/CanHardwareObject/*"!]
    [!VAR "OuterLoopCounter" = "$OuterLoopCounter + 1"!]
    [!VAR "InnerLoopCounter" = "0"!]
    [!VAR "Matchcounter" = "0"!]
    [!VAR "Name" = "node:name(.)"!]
    [!LOOP "../../../*/CanHardwareObject/*"!]
        [!VAR "InnerLoopCounter" = "$InnerLoopCounter + 1"!]
        [!IF "$OuterLoopCounter >= $InnerLoopCounter"!]
            [!IF "($Name = node:name(.))"!]
                [!VAR "Matchcounter" = "$Matchcounter + 1"!]
            [!ENDIF!]
        [!ENDIF!]
    [!ENDLOOP!]
    [!IF "$Matchcounter != 1"!]
    [!WARNING!] Some MBs have identical name. Should avoid this because of multiple generated DEFINEs with the same name![!ENDWARNING!]
    [!ENDIF!]
[!ENDLOOP!]
[!ENDNOCODE!]

[!NOCODE!]
[!LOOP "CanConfigSet/*"!]
    [!VAR "MaxObjectIdForReceiveHO" = "0"!]
    [!LOOP "CanHardwareObject/*"!]
        [!IF "CanObjectType = 'RECEIVE'"!]
            [!IF "$MaxObjectIdForReceiveHO < CanObjectId"!]
                [!VAR "MaxObjectIdForReceiveHO" = "CanObjectId"!]
            [!ENDIF!]
        [!ENDIF!]
    [!ENDLOOP!]
    [!LOOP "CanHardwareObject/*"!]
        [!IF "CanObjectType = 'TRANSMIT'"!]
            [!IF "$MaxObjectIdForReceiveHO >= CanObjectId"!]
                [!ERROR!]
                The HRH and HTH Ids are defined under two different name-spaces (Refer to CAN326).
                Example: HRH0-0, HRH1-1, HTH0-2, HTH1-3.
                The HRHs of all controllers are grouped before the HTHs of all controllers
                    (there must not be any HTH of any controller with an object ID lower than
                    that of any HRH configured for this driver).
                [!ENDERROR!]
            [!ENDIF!]
        [!ENDIF!]
    [!ENDLOOP!]
    [!LOOP "CanHardwareObject/*"!]
        [!IF "@index > 0"!]
          [!FOR "x" = "0" TO "num:i(@index)"!]
            [!IF "num:i(CanObjectId) = num:i(../*[position() = ($x+1)]/CanObjectId)"!]
                [!IF "contains(node:path(node:ref(CanControllerRef)), node:path(node:ref(../*[position() = ($x+1)]/CanControllerRef)))"!]
                [!ELSE!]
                    [!ERROR!]
                    If Multiplex transmission = ON, the Hardware Objects that has the same CanObjectId must refer to the same controller, and must be of type TRANSMIT.
                    CanHardwareOblect "[!"node:name(.)"!]" and "[!"node:name(../*[position() = ($x+1)])"!]" have the same CanObjectId but refer to different controllers.
                    [!ENDERROR!]
                [!ENDIF!]
            [!ENDIF!]
          [!ENDFOR!]
        [!ENDIF!]
    [!ENDLOOP!]
[!ENDLOOP!]
[!ENDNOCODE!]

[!NOCODE!]
[!LOOP "CanConfigSet/*"!]
    [!LOOP "CanHardwareObject/*"!]
        [!IF "CanObjectType = 'RECEIVE'"!]
[!CODE!]
/* @violates @ref Can_Cfg_h_REF_3 Violates MISRA 2004 Required Rule 1.4, Identifier clash */
/* @violates @ref Can_Cfg_h_REF_5 This is required as per autosar Requirement. */
#define CanConf_CanHwObj_[!"@name"!] ([!"num:i(CanObjectId)"!]U) /* RECEIVE object of Can Controller ID = [!"num:i(node:ref(CanControllerRef)/CanControllerId)"!] */
[!ENDCODE!]
        [!ENDIF!]
    [!ENDLOOP!]
[!ENDLOOP!]
[!LOOP "CanConfigSet/*"!]
    [!LOOP "CanHardwareObject/*"!]
        [!IF "CanObjectType = 'TRANSMIT'"!]
[!CODE!]
/* @violates @ref Can_Cfg_h_REF_3 Violates MISRA 2004 Required Rule 1.4, Identifier clash */
/* @violates @ref Can_Cfg_h_REF_5 This is required as per autosar Requirement. */
#define CanConf_CanHwObj_[!"@name"!] ([!"num:i(CanObjectId)"!]U) /* TRANSMIT object of Can Controller ID = [!"num:i(node:ref(CanControllerRef)/CanControllerId)"!] */
[!ENDCODE!]
        [!ENDIF!]
    [!ENDLOOP!]
[!ENDLOOP!]
[!ENDNOCODE!]

/*
* @brief          Extended identifiers.
* @details        Extended identifiers.
                   - (STD_ON)  - if at least one extended identifier is used.
                   - (STD_OFF) - if no extended identifiers are used at all
                  If no extended identifiers are used then the IDs and MASKs can be stored in uint16 rather than uint32.
*
* @implements     DCAN02610
*/
#define CAN_EXTENDEDID [!IF "CanGeneral/CanExtendedIDSupport = 'true'"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]

/*
* @brief          Switches the Can_ChangeBaudrate API and Can_CheckBaudRate API ON or OFF.
* @details        (CAN460) Configuration of Can_CheckBaudrate(Controller, Baudrate): If Can supports changing of the
                  baudrate and thus this service, shall be configurable via CAN_CHANGE_BAUDRATE_SUPPORT
*
* @implements     DCAN02903
*/
#define CAN_CHANGE_BAUDRATE_API [!IF "CanGeneral/CanChangeBaudrateApi = 'true'"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]


/*
* @brief          Switches the Development Error Detection and Notification ON or OFF.
* @details        (CAN028) Call the Development Error Tracer when DET is switched on and the Can module detects an error.
                  (CAN082) The detection of development errors is configurable (ON / OFF) at pre- compile time.
                  The switch CanDevErrorDetection (see chapter 10) shall activate or deactivate the detection of all development errors.
*
* @implements     DCAN01403, DCAN01013
*/
#define CAN_DEV_ERROR_DETECT [!IF "CanGeneral/CanDevErrorDetection = 'true'"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]

/*
* @brief          CAN driver support for wakeup over CAN Bus.
* @details        CAN driver support for wakeup over CAN Bus.
*
* @implements     DCAN02611
*/
#define CAN_WAKEUP_SUPPORT [!IF "CanConfigSet/*/CanController/*/CanWakeupSupport = 'true'"!][!IF "ecu:get('Can.CanConfig.InternalWakeupSupport')='STD_ON'"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!][!ELSE!](STD_OFF)[!ENDIF!]

/*
* @brief          Extended number of can hardware objects
* @details        Extended number of can hardware objects:
                   - STD_ON if more than 256 can hardware objects are needed (up to 65536)
                   - STD_OFF if no more than 256 can hardware objects are needed
                  The specification only allows up to 256 can hardware objects. The driver supports a non-standard extension of this limit.
*
* @implements     DCAN02612
*/
#define CAN_MBCOUNTEXTENSION [!IF "CanGeneral/CanMBCountExtensionSupport = 'true'"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]

/*
* @brief          Support for version info API
* @details        Switches the Can_GetVersionInfo() API ON or OFF.
*
* @implements     DCAN02051
*/
#define CAN_VERSION_INFO_API [!IF "CanGeneral/CanVersionInfoApi = 'true'"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]

/*
* @brief          Support for Multiplexed Transmision
* @details        MB set for Tx is put on bus from any TxMB that is available (free).
*                 (CAN277) The Can module shall allow that the functionality Multiplexed Transmission is statically configurable (ON | OFF) at pre-compile time.
*
* @implements     DCAN01114
*/
#define CAN_MULTIPLEXED_TRANSMISSION [!IF "CanGeneral/CanMultiplexedTransmission = 'true'"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]

/*
* @brief          Support for Transmision Cancellation
* @details        Support for Transmision Cancellation
*                 (CAN278) The Can module shall allow that the functionality Transmit Cancellation is statically configurable (ON | OFF) at pre-compile time.
*
* @implements     DCAN01068
*/
#define CAN_HW_TRANSMIT_CANCELLATION [!IF "CanGeneral/CanHardwareCancellation = 'true'"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]

/*
* @brief          Support for Identical Id Cancellation
* @details        Enables/disables cancellation of pending PDUs with identical ID.
*
* @implements     DCAN02050
*/
#define CAN_IDENTICAL_ID_CANCELLATION [!IF "CanGeneral/CanIdenticalIdCancellation = 'true'"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]

/*
* @brief          Support for Special MB Abort API
* @details        Enable an additional API, to write an ABORT code (b1001) to the MBCB filed of the MB to abort a message transmission.
*
* @implements     DCAN02613
*/
#define CAN_API_ENABLE_ABORT_MB [!IF "(CanGeneral/CanHardwareCancellation = 'true') and (CanGeneral/CanApiEnableMbAbort = 'true')"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]

/*
* @brief          Support for MB Abort  API
* @details         This parameter is enabled only if CanMultiplexedTransmission=STD_ON and aborts only one message buffer
* @implements   DCAN02060
*/
#define Can_Abort_Only_One_MB [!IF "CanGeneral/CanAbortOnlyOneMB = 'true'"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]
/*
* @brief          Instance # of the driver - used for Det_ReportError().
* @details        Instance # of the driver - used for Det_ReportError().
*
* @implements     DCAN02614
*/
#define CAN_INSTANCE ([!"num:i(CanGeneral/CanIndex)"!]U)

/*
* @brief          Platform support mix of controllers with 64 and 32 MBs.
* @details        Platform support mix of controllers with 64 and 32 MBs.
*
* @implements     DCAN02615
*/
#define CAN_MIX_MB_SUPPORT  [!IF "ecu:get('Can.CanConfig.MixMB')='STD_ON'"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]

/*
@brief    Support for esr read status API
*/
#define CAN_API_ERROR_STATUS  [!IF "NonAutosar/CanApiErrorStatus = 'true'"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]
/*
* @brief    Support for checking TX message cancelation
*/
#define CAN_API_TXCANCEL_CHECK  [!IF "NonAutosar/CanApiCheckTxCancel = 'true'"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]

/*
* @brief          Maximum number of Message Buffers configured.
* @details        Maximum number of Message Buffers configured.
*
* @implements     DCAN02616
*/[!VAR "max_ctrl" = "ecu:get('Can.CanConfigSet.CanController')"!]
[!LOOP "CanConfigSet/*"!][!VAR "ctrls" = "num:i(count(CanController/*))"!][!VAR "mbs" = "num:i(count(CanHardwareObject/*))"!]
[!IF "( ($ctrls > $max_ctrl) or ($mbs > ($ctrls*(ecu:get('Can.CanConfigSet.CanMB')))) )"!]
    [!ERROR!]Too many MBs for the number of controllers configured.[!ENDERROR!]
[!ELSE!]#define CAN_MAXMBCOUNT_[!"@index"!] [!"num:i(count(CanHardwareObject/*))"!]U[!ENDIF!]
[!ENDLOOP!]

/*
* @brief          Maximum possible Message Buffers per controller specific to this platform.
* @details        Maximum possible Message Buffers per controller specific to this platform.
*
* @implements     DCAN02617
*/
/* @violates @ref Can_Cfg_h_REF_5 This is required as per autosar Requirement. */
#define CAN_MAXMB_SUPPORTED ([!"num:i(ecu:get('Can.CanConfigSet.CanMB'))"!]U)

[!VAR "Can_hardware_ob" = "0"!]
[!LOOP "CanConfigSet/*"!]
    [!FOR "controllerid" = "0" TO "num:i(count(CanController/*) - 1)"!]
        [!VAR "controllercount" = "0"!]
        [!LOOP "CanController/*"!]
            [!IF "CanControllerActivation = 'true' and CanControllerId = $controllerid"!]
                [!NOCODE!][!VAR "maxmbcount" = "0"!]
                [!LOOP "../../CanHardwareObject/*"!]
                        [!SELECT "node:ref(CanControllerRef)"!]
                            [!IF "num:i(CanControllerId) = num:i($controllerid)"!]
                                [!VAR "maxmbcount" = "$maxmbcount+1"!]
                            [!ENDIF!]
                    [!ENDSELECT!]
                [!ENDLOOP!]
                [!ENDNOCODE!]
                [!IF "CanControllerRxFifoEnable = 'true'"!][!VAR "maxmbcount" = "$maxmbcount+7"!][!ENDIF!]
                [!IF "$Can_hardware_ob < $maxmbcount"!]
                [!VAR "Can_hardware_ob" = "$maxmbcount"!]
                [!ENDIF!]
            [!ENDIF!]
        [!ENDLOOP!]
    [!ENDFOR!]
[!ENDLOOP!]
/*
* @brief          Maximum number of Message Buffers configured.
* @details        Maximum number of Message Buffers configured.
*
* @implements     DCAN02061
*/
#define CAN_MAXMB_CONFIGURED ([!"num:i($Can_hardware_ob)"!]U)

/*
* @brief          Maximum possible controllers per specific derivative.
* @details        Maximum possible controllers per specific derivative.
*
* @implements     DCAN02618
*/
#define CAN_MAXCTRL_SUPPORTED ([!"num:i(ecu:get('Can.CanConfigSet.CanController'))"!]U)

/**
* @brief          Maximum No. of supported controllers (vary according to Processor Family).
* @details        Maximum No. of supported controllers (vary according to Processor Family).
*
* @implements     DCAN02619
*/[!IF "IMPLEMENTATION_CONFIG_VARIANT='VariantPreCompile'"!]
[!SELECT "CanConfigSet/*[1]"!][!VAR "ctrls" = "num:i(count(CanController/*))"!]
[!IF "$ctrls > $max_ctrl"!][!ERROR!]Target supports maximum [!"num:i(ecu:get('Can.CanConfigSet.CanController'))"!] controllers.[!ENDERROR!]
[!ELSE!]#define CAN_MAXCONTROLLERCOUNT_0 [!"$ctrls"!]U[!ENDIF!][!ENDSELECT!]
[!ELSE!]
[!LOOP "CanConfigSet/*"!][!VAR "ctrls" = "num:i(count(CanController/*))"!]
[!IF "$ctrls > $max_ctrl"!][!ERROR!]Target supports maximum [!"num:i(ecu:get('Can.CanConfigSet.CanController'))"!] controllers.[!ENDERROR!]
[!ELSE!]#define CAN_MAXCONTROLLERCOUNT_[!"@index"!] [!"$ctrls"!]U[!ENDIF!][!ENDLOOP!]
[!ENDIF!]

/*
* @brief          Maximum No. of controllers Configured
* @details      Maximum No. of controllers Configured
*
* @implements     DCAN02062
*/
[!VAR "flexcans" = "0"!]
[!LOOP "CanConfigSet/*"!][!VAR "flexcans" = "num:i(count(CanController/*))"!] [!ENDLOOP!]
#define CAN_MAXCTRL_CONFIGURED ([!"$flexcans"!]U)


/**
* @brief          Hardware events detected by an interrupt or by polling
* @details        (CAN099) The hardware events may be detected by an interrupt or by polling status flags of the hardware objects.
*                 The configuration possibilities regarding polling is hardware dependent (i.e. which events can be polled, which events need to be polled), and not restricted by this standard.
*                 (CAN007)It shall be possible to configure the driver such that no interrupts at all are used (complete polling).
*
* @implements     DCAN01116, DCAN01050
*/
[!NOCODE!][!VAR "int_en_a"="0"!][!VAR "int_en_b"="0"!][!VAR "int_en_c"="0"!][!VAR "int_en_d"="0"!][!VAR "int_en_e"="0"!][!VAR "int_en_f"="0"!][!VAR "int_en_g"="0"!][!VAR "int_en_h"="0"!][!VAR "pol_en"="0"!]
[!SELECT "CanConfigSet/*[1]"!]
    [!LOOP "CanController/*"!]
        [!IF "CanTxProcessing = 'Polling'"!]
            [!VAR "pol_en" = "1"!]
        [!ENDIF!]
        [!IF "CanHwChannel = 'FlexCAN_A'"!]
            [!IF "CanTxProcessing = 'Interrupt'"!]
                [!VAR "int_en_a" = "1"!]
            [!ELSE!]
                [!VAR "int_en_a" = "2"!]
            [!ENDIF!]
        [!ENDIF!]
        [!IF "CanHwChannel = 'FlexCAN_B'"!]
            [!IF "CanTxProcessing = 'Interrupt'"!]
                [!VAR "int_en_b" = "1"!]
            [!ELSE!]
                [!VAR "int_en_b" = "2"!]
            [!ENDIF!]
        [!ENDIF!]
        [!IF "CanHwChannel = 'FlexCAN_C'"!]
            [!IF "CanTxProcessing = 'Interrupt'"!]
                [!VAR "int_en_c" = "1"!]
            [!ELSE!]
                [!VAR "int_en_c" = "2"!]
            [!ENDIF!]
        [!ENDIF!]
        [!IF "CanHwChannel = 'FlexCAN_D'"!]
            [!IF "CanTxProcessing = 'Interrupt'"!]
                [!VAR "int_en_d" = "1"!]
            [!ELSE!]
                [!VAR "int_en_d" = "2"!]
            [!ENDIF!]
        [!ENDIF!]
        [!IF "CanHwChannel = 'FlexCAN_E'"!]
            [!IF "CanTxProcessing = 'Interrupt'"!]
                [!VAR "int_en_e" = "1"!]
            [!ELSE!]
                [!VAR "int_en_e" = "2"!]
            [!ENDIF!]
        [!ENDIF!]
        [!IF "CanHwChannel = 'FlexCAN_F'"!]
            [!IF "CanTxProcessing = 'Interrupt'"!]
                [!VAR "int_en_f" = "1"!]
            [!ELSE!]
                [!VAR "int_en_f" = "2"!]
            [!ENDIF!]
        [!ENDIF!]
        [!IF "CanHwChannel = 'FlexCAN_G'"!]
            [!IF "CanTxProcessing = 'Interrupt'"!]
                [!VAR "int_en_g" = "1"!]
            [!ELSE!]
                [!VAR "int_en_g" = "2"!]
            [!ENDIF!]
        [!ENDIF!]
        [!IF "CanHwChannel = 'FlexCAN_H'"!]
            [!IF "CanTxProcessing = 'Interrupt'"!]
                [!VAR "int_en_h" = "1"!]
            [!ELSE!]
                [!VAR "int_en_h" = "2"!]
            [!ENDIF!]
        [!ENDIF!]
    [!ENDLOOP!]
[!ENDSELECT!][!ENDNOCODE!]

/**
* @brief          This macros enable Interrupts for controllers if Tx processing is set to Interrupt Mode.
* @details        This macros enable Interrupts for controllers if Tx processing is set to Interrupt Mode.
*
* @implements     DCAN02620
*/
[!IF "$int_en_a!=0"!]#define CAN_A_TXINT_SUPPORTED  [!IF "$int_en_a = 1"!](STD_ON)[!ELSEIF "$int_en_a = 2"!](STD_OFF)[!ENDIF!][!ENDIF!]
[!IF "$int_en_b!=0"!]#define CAN_B_TXINT_SUPPORTED  [!IF "$int_en_b = 1"!](STD_ON)[!ELSEIF "$int_en_b = 2"!](STD_OFF)[!ENDIF!][!ENDIF!]
[!IF "$int_en_c!=0"!]#define CAN_C_TXINT_SUPPORTED  [!IF "$int_en_c = 1"!](STD_ON)[!ELSEIF "$int_en_c = 2"!](STD_OFF)[!ENDIF!][!ENDIF!]
[!IF "$int_en_d!=0"!]#define CAN_D_TXINT_SUPPORTED  [!IF "$int_en_d = 1"!](STD_ON)[!ELSEIF "$int_en_d = 2"!](STD_OFF)[!ENDIF!][!ENDIF!]
[!IF "$int_en_e!=0"!]#define CAN_E_TXINT_SUPPORTED  [!IF "$int_en_e = 1"!](STD_ON)[!ELSEIF "$int_en_e = 2"!](STD_OFF)[!ENDIF!][!ENDIF!]
[!IF "$int_en_f!=0"!]#define CAN_F_TXINT_SUPPORTED  [!IF "$int_en_f = 1"!](STD_ON)[!ELSEIF "$int_en_f = 2"!](STD_OFF)[!ENDIF!][!ENDIF!]
[!IF "$int_en_g!=0"!]#define CAN_G_TXINT_SUPPORTED  [!IF "$int_en_g = 1"!](STD_ON)[!ELSEIF "$int_en_g = 2"!](STD_OFF)[!ENDIF!][!ENDIF!]
[!IF "$int_en_h!=0"!]#define CAN_H_TXINT_SUPPORTED  [!IF "$int_en_h = 1"!](STD_ON)[!ELSEIF "$int_en_h = 2"!](STD_OFF)[!ENDIF!][!ENDIF!]

/*
* @brief          This macro enables Can_MainFunction_Write() if at least one controller is set to process Tx in Polling Mode.
* @details        This macro enables Can_MainFunction_Write() if at least one controller is set to process Tx in Polling Mode.
*
* @implements     DCAN02621
*/
#define CAN_TXPOLL_SUPPORTED   [!IF "$pol_en = 1"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]

[!NOCODE!][!VAR "int_en_a"="0"!][!VAR "int_en_b"="0"!][!VAR "int_en_c"="0"!][!VAR "int_en_d"="0"!][!VAR "int_en_e"="0"!][!VAR "int_en_f"="0"!][!VAR "int_en_g"="0"!][!VAR "int_en_h"="0"!][!VAR "pol_en"="0"!]
[!SELECT "CanConfigSet/*[1]"!]
    [!LOOP "CanController/*"!]
        [!IF "CanRxProcessing = 'Polling'"!]
            [!VAR "pol_en" = "1"!]
        [!ENDIF!]
        [!IF "CanHwChannel = 'FlexCAN_A'"!]
            [!IF "CanRxProcessing = 'Interrupt'"!]
                [!VAR "int_en_a" = "1"!]
            [!ELSE!]
                [!VAR "int_en_a" = "2"!]
            [!ENDIF!]
        [!ENDIF!]
        [!IF "CanHwChannel = 'FlexCAN_B'"!]
            [!IF "CanRxProcessing = 'Interrupt'"!]
                [!VAR "int_en_b" = "1"!]
            [!ELSE!]
                [!VAR "int_en_b" = "2"!]
            [!ENDIF!]
        [!ENDIF!]
        [!IF "CanHwChannel = 'FlexCAN_C'"!]
            [!IF "CanRxProcessing = 'Interrupt'"!]
                [!VAR "int_en_c" = "1"!]
            [!ELSE!]
                [!VAR "int_en_c" = "2"!]
            [!ENDIF!]
        [!ENDIF!]
        [!IF "CanHwChannel = 'FlexCAN_D'"!]
            [!IF "CanRxProcessing = 'Interrupt'"!]
                [!VAR "int_en_d" = "1"!]
            [!ELSE!]
                [!VAR "int_en_d" = "2"!]
            [!ENDIF!]
        [!ENDIF!]
        [!IF "CanHwChannel = 'FlexCAN_E'"!]
            [!IF "CanRxProcessing = 'Interrupt'"!]
                [!VAR "int_en_e" = "1"!]
            [!ELSE!]
                [!VAR "int_en_e" = "2"!]
            [!ENDIF!]
        [!ENDIF!]
        [!IF "CanHwChannel = 'FlexCAN_F'"!]
            [!IF "CanRxProcessing = 'Interrupt'"!]
                [!VAR "int_en_f" = "1"!]
            [!ELSE!]
                [!VAR "int_en_f" = "2"!]
            [!ENDIF!]
        [!ENDIF!]
        [!IF "CanHwChannel = 'FlexCAN_G'"!]
            [!IF "CanRxProcessing = 'Interrupt'"!]
                [!VAR "int_en_g" = "1"!]
            [!ELSE!]
                [!VAR "int_en_g" = "2"!]
            [!ENDIF!]
        [!ENDIF!]
        [!IF "CanHwChannel = 'FlexCAN_H'"!]
            [!IF "CanRxProcessing = 'Interrupt'"!]
                [!VAR "int_en_h" = "1"!]
            [!ELSE!]
                [!VAR "int_en_h" = "2"!]
            [!ENDIF!]
        [!ENDIF!]
    [!ENDLOOP!]
[!ENDSELECT!][!ENDNOCODE!]

/**
* @brief          This macros enable Interrupts for controllers if Rx processing is set to Interrupt Mode.
* @details        This macros enable Interrupts for controllers if Rx processing is set to Interrupt Mode.
*
* @implements     DCAN02622
*/
[!IF "$int_en_a!=0"!]#define CAN_A_RXINT_SUPPORTED  [!IF "$int_en_a = 1"!](STD_ON)[!ELSEIF "$int_en_a = 2"!](STD_OFF)[!ENDIF!][!ENDIF!]
[!IF "$int_en_b!=0"!]#define CAN_B_RXINT_SUPPORTED  [!IF "$int_en_b = 1"!](STD_ON)[!ELSEIF "$int_en_b = 2"!](STD_OFF)[!ENDIF!][!ENDIF!]
[!IF "$int_en_c!=0"!]#define CAN_C_RXINT_SUPPORTED  [!IF "$int_en_c = 1"!](STD_ON)[!ELSEIF "$int_en_c = 2"!](STD_OFF)[!ENDIF!][!ENDIF!]
[!IF "$int_en_d!=0"!]#define CAN_D_RXINT_SUPPORTED  [!IF "$int_en_d = 1"!](STD_ON)[!ELSEIF "$int_en_d = 2"!](STD_OFF)[!ENDIF!][!ENDIF!]
[!IF "$int_en_e!=0"!]#define CAN_E_RXINT_SUPPORTED  [!IF "$int_en_e = 1"!](STD_ON)[!ELSEIF "$int_en_e = 2"!](STD_OFF)[!ENDIF!][!ENDIF!]
[!IF "$int_en_f!=0"!]#define CAN_F_RXINT_SUPPORTED  [!IF "$int_en_f = 1"!](STD_ON)[!ELSEIF "$int_en_f = 2"!](STD_OFF)[!ENDIF!][!ENDIF!]
[!IF "$int_en_g!=0"!]#define CAN_G_RXINT_SUPPORTED  [!IF "$int_en_g = 1"!](STD_ON)[!ELSEIF "$int_en_g = 2"!](STD_OFF)[!ENDIF!][!ENDIF!]
[!IF "$int_en_h!=0"!]#define CAN_H_RXINT_SUPPORTED  [!IF "$int_en_h = 1"!](STD_ON)[!ELSEIF "$int_en_h = 2"!](STD_OFF)[!ENDIF!][!ENDIF!]
/*
* @brief          This macro enables Can_MainFunction_Read() if at least one controller is set to process Rx in Polling Mode.
* @details        This macro enables Can_MainFunction_Read() if at least one controller is set to process Rx in Polling Mode.
*
* @implements     DCAN02623
*/
#define CAN_RXPOLL_SUPPORTED   [!IF "$pol_en = 1"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]

[!NOCODE!][!VAR "int_en_a"="0"!][!VAR "int_en_b"="0"!][!VAR "int_en_c"="0"!][!VAR "int_en_d"="0"!][!VAR "int_en_e"="0"!][!VAR "int_en_f"="0"!][!VAR "int_en_g"="0"!][!VAR "int_en_h"="0"!][!VAR "pol_en"="0"!]
[!SELECT "CanConfigSet/*[1]"!]
    [!LOOP "CanController/*"!]
        [!IF "CanBusoffProcessing = 'Polling'"!]
            [!VAR "pol_en" = "1"!]
        [!ENDIF!]
        [!IF "CanHwChannel = 'FlexCAN_A'"!]
            [!IF "CanBusoffProcessing = 'Interrupt'"!]
                [!VAR "int_en_a" = "1"!]
            [!ELSE!]
                [!VAR "int_en_a" = "2"!]
            [!ENDIF!]
        [!ENDIF!]
        [!IF "CanHwChannel = 'FlexCAN_B'"!]
            [!IF "CanBusoffProcessing = 'Interrupt'"!]
                [!VAR "int_en_b" = "1"!]
            [!ELSE!]
                [!VAR "int_en_b" = "2"!]
            [!ENDIF!]
        [!ENDIF!]
        [!IF "CanHwChannel = 'FlexCAN_C'"!]
            [!IF "CanBusoffProcessing = 'Interrupt'"!]
                [!VAR "int_en_c" = "1"!]
            [!ELSE!]
                [!VAR "int_en_c" = "2"!]
            [!ENDIF!]
        [!ENDIF!]
        [!IF "CanHwChannel = 'FlexCAN_D'"!]
            [!IF "CanBusoffProcessing = 'Interrupt'"!]
                [!VAR "int_en_d" = "1"!]
            [!ELSE!]
                [!VAR "int_en_d" = "2"!]
            [!ENDIF!]
        [!ENDIF!]
        [!IF "CanHwChannel = 'FlexCAN_E'"!]
            [!IF "CanBusoffProcessing = 'Interrupt'"!]
                [!VAR "int_en_e" = "1"!]
            [!ELSE!]
                [!VAR "int_en_e" = "2"!]
            [!ENDIF!]
        [!ENDIF!]
        [!IF "CanHwChannel = 'FlexCAN_F'"!]
            [!IF "CanBusoffProcessing = 'Interrupt'"!]
                [!VAR "int_en_f" = "1"!]
            [!ELSE!]
                [!VAR "int_en_f" = "2"!]
            [!ENDIF!]
        [!ENDIF!]
        [!IF "CanHwChannel = 'FlexCAN_G'"!]
            [!IF "CanBusoffProcessing = 'Interrupt'"!]
                [!VAR "int_en_g" = "1"!]
            [!ELSE!]
                [!VAR "int_en_g" = "2"!]
            [!ENDIF!]
        [!ENDIF!]
        [!IF "CanHwChannel = 'FlexCAN_H'"!]
            [!IF "CanBusoffProcessing = 'Interrupt'"!]
                [!VAR "int_en_h" = "1"!]
            [!ELSE!]
                [!VAR "int_en_h" = "2"!]
            [!ENDIF!]
        [!ENDIF!]
    [!ENDLOOP!]
[!ENDSELECT!][!ENDNOCODE!]

/**
* @brief          This macros enable Interrupts for controllers if BusOff processing is set to Interrupt Mode.
* @details        This macros enable Interrupts for controllers if BusOff processing is set to Interrupt Mode.
*
* @implements     DCAN02624
*/
[!IF "$int_en_a!=0"!]#define CAN_A_BUSOFFINT_SUPPORTED  [!IF "$int_en_a = 1"!](STD_ON)[!ELSEIF "$int_en_a = 2"!](STD_OFF)[!ENDIF!][!ENDIF!]
[!IF "$int_en_b!=0"!]#define CAN_B_BUSOFFINT_SUPPORTED  [!IF "$int_en_b = 1"!](STD_ON)[!ELSEIF "$int_en_b = 2"!](STD_OFF)[!ENDIF!][!ENDIF!]
[!IF "$int_en_c!=0"!]#define CAN_C_BUSOFFINT_SUPPORTED  [!IF "$int_en_c = 1"!](STD_ON)[!ELSEIF "$int_en_c = 2"!](STD_OFF)[!ENDIF!][!ENDIF!]
[!IF "$int_en_d!=0"!]#define CAN_D_BUSOFFINT_SUPPORTED  [!IF "$int_en_d = 1"!](STD_ON)[!ELSEIF "$int_en_d = 2"!](STD_OFF)[!ENDIF!][!ENDIF!]
[!IF "$int_en_e!=0"!]#define CAN_E_BUSOFFINT_SUPPORTED  [!IF "$int_en_e = 1"!](STD_ON)[!ELSEIF "$int_en_e = 2"!](STD_OFF)[!ENDIF!][!ENDIF!]
[!IF "$int_en_f!=0"!]#define CAN_F_BUSOFFINT_SUPPORTED  [!IF "$int_en_f = 1"!](STD_ON)[!ELSEIF "$int_en_f = 2"!](STD_OFF)[!ENDIF!][!ENDIF!]
[!IF "$int_en_g!=0"!]#define CAN_G_BUSOFFINT_SUPPORTED  [!IF "$int_en_g = 1"!](STD_ON)[!ELSEIF "$int_en_g = 2"!](STD_OFF)[!ENDIF!][!ENDIF!]
[!IF "$int_en_h!=0"!]#define CAN_H_BUSOFFINT_SUPPORTED  [!IF "$int_en_h = 1"!](STD_ON)[!ELSEIF "$int_en_h = 2"!](STD_OFF)[!ENDIF!][!ENDIF!]

/*
* @brief          This macro enables Can_MainFunction_BusOff() if at least one controller is set to process BusOff in Polling Mode.
* @details        This macro enables Can_MainFunction_BusOff() if at least one controller is set to process BusOff in Polling Mode.
*
* @implements     DCAN02625
*/
#define CAN_BUSOFFPOLL_SUPPORTED   [!IF "$pol_en = 1"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]

[!NOCODE!][!VAR "int_en_a"="0"!][!VAR "int_en_b"="0"!][!VAR "int_en_c"="0"!][!VAR "int_en_d"="0"!][!VAR "int_en_e"="0"!][!VAR "int_en_f"="0"!][!VAR "int_en_g"="0"!][!VAR "int_en_h"="0"!][!VAR "pol_en"="0"!]
[!SELECT "CanConfigSet/*[1]"!]
    [!LOOP "CanController/*"!]
        [!IF "CanWakeupProcessing = 'Polling'"!]
                [!VAR "pol_en" = "1"!]
        [!ENDIF!]
        [!IF "CanHwChannel = 'FlexCAN_A'"!]
            [!IF "CanWakeupProcessing = 'Interrupt'"!]
                [!VAR "int_en_a" = "1"!]
            [!ELSE!]
                [!VAR "int_en_a" = "2"!]
            [!ENDIF!]
        [!ENDIF!]

        [!IF "CanHwChannel = 'FlexCAN_B'"!]
            [!IF "CanWakeupProcessing = 'Interrupt'"!]
                [!VAR "int_en_b" = "1"!]
            [!ELSE!]
                [!VAR "int_en_b" = "2"!]
            [!ENDIF!]
        [!ENDIF!]

        [!IF "CanHwChannel = 'FlexCAN_C'"!]
            [!IF "CanWakeupProcessing = 'Interrupt'"!]
                [!VAR "int_en_c" = "1"!]
            [!ELSE!]
                [!VAR "int_en_c" = "2"!]
            [!ENDIF!]
        [!ENDIF!]

        [!IF "CanHwChannel = 'FlexCAN_D'"!]
            [!IF "CanWakeupProcessing = 'Interrupt'"!]
                [!VAR "int_en_d" = "1"!]
            [!ELSE!]
                [!VAR "int_en_d" = "2"!]
            [!ENDIF!]
        [!ENDIF!]

        [!IF "CanHwChannel = 'FlexCAN_E'"!]
            [!IF "CanWakeupProcessing = 'Interrupt'"!]
                [!VAR "int_en_e" = "1"!]
            [!ELSE!]
                [!VAR "int_en_e" = "2"!]
            [!ENDIF!]
        [!ENDIF!]

        [!IF "CanHwChannel = 'FlexCAN_F'"!]
            [!IF "CanWakeupProcessing = 'Interrupt'"!]
                [!VAR "int_en_f" = "1"!]
            [!ELSE!]
                [!VAR "int_en_f" = "2"!]
            [!ENDIF!]
        [!ENDIF!]

        [!IF "CanHwChannel = 'FlexCAN_G'"!]
            [!IF "CanWakeupProcessing = 'Interrupt'"!]
                [!VAR "int_en_g" = "1"!]
            [!ELSE!]
                [!VAR "int_en_g" = "2"!]
            [!ENDIF!]
        [!ENDIF!]

        [!IF "CanHwChannel = 'FlexCAN_H'"!]
            [!IF "CanWakeupProcessing = 'Interrupt'"!]
                [!VAR "int_en_h" = "1"!]
            [!ELSE!]
                [!VAR "int_en_h" = "2"!]
            [!ENDIF!]
        [!ENDIF!]

    [!ENDLOOP!]
[!ENDSELECT!][!ENDNOCODE!]
/**
* @brief          This macros enable Interrupts for controllers if Wakeup processing is set to Interrupt Mode.
* @details        This macros enable Interrupts for controllers if Wakeup processing is set to Interrupt Mode.
*
* @implements     DCAN02626
*/
[!IF "$int_en_a!=0"!]#define CAN_A_WAKEUPINT_SUPPORTED  [!IF "$int_en_a = 1"!](STD_ON)[!ELSEIF "$int_en_a = 2"!](STD_OFF)[!ENDIF!][!ENDIF!]
[!IF "$int_en_b!=0"!]#define CAN_B_WAKEUPINT_SUPPORTED  [!IF "$int_en_b = 1"!](STD_ON)[!ELSEIF "$int_en_b = 2"!](STD_OFF)[!ENDIF!][!ENDIF!]
[!IF "$int_en_c!=0"!]#define CAN_C_WAKEUPINT_SUPPORTED  [!IF "$int_en_c = 1"!](STD_ON)[!ELSEIF "$int_en_c = 2"!](STD_OFF)[!ENDIF!][!ENDIF!]
[!IF "$int_en_d!=0"!]#define CAN_D_WAKEUPINT_SUPPORTED  [!IF "$int_en_d = 1"!](STD_ON)[!ELSEIF "$int_en_d = 2"!](STD_OFF)[!ENDIF!][!ENDIF!]
[!IF "$int_en_e!=0"!]#define CAN_E_WAKEUPINT_SUPPORTED  [!IF "$int_en_e = 1"!](STD_ON)[!ELSEIF "$int_en_e = 2"!](STD_OFF)[!ENDIF!][!ENDIF!]
[!IF "$int_en_f!=0"!]#define CAN_F_WAKEUPINT_SUPPORTED  [!IF "$int_en_f = 1"!](STD_ON)[!ELSEIF "$int_en_f = 2"!](STD_OFF)[!ENDIF!][!ENDIF!]
[!IF "$int_en_g!=0"!]#define CAN_G_WAKEUPINT_SUPPORTED  [!IF "$int_en_g = 1"!](STD_ON)[!ELSEIF "$int_en_g = 2"!](STD_OFF)[!ENDIF!][!ENDIF!]
[!IF "$int_en_h!=0"!]#define CAN_H_WAKEUPINT_SUPPORTED  [!IF "$int_en_h = 1"!](STD_ON)[!ELSEIF "$int_en_h = 2"!](STD_OFF)[!ENDIF!][!ENDIF!]

/*
* @brief          This macro enables Can_MainFunction_Wakeup() if at least one controller is set to process WakeUp in Polling Mode.
* @details        This macro enables Can_MainFunction_Wakeup() if at least one controller is set to process WakeUp in Polling Mode.
*
* @implements     DCAN02627
*/
#define CAN_WAKEUPPOLL_SUPPORTED   [!IF "$pol_en = 1"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]

/*
* @brief          Maximum number of MB Filters configured.
* @details        Maximum number of MB Filters configured.
*
* @implements     DCAN02628
*/[!LOOP "CanConfigSet/*"!]
#define CAN_MAXFILTERCOUNT_[!"@index"!] [!"num:i(count(CanController/*/CanFilterMask/*))"!]U
[!ENDLOOP!]

/**
* @brief          Maximum number of baudrate configured.
* @details        Maximum number of baudrate configured.
*                 Controller Baudrates configured are in kbps
*
* @implements     DCAN02008
*/[!NOCODE!][!IF "IMPLEMENTATION_CONFIG_VARIANT='VariantPreCompile'"!]
[!SELECT "CanConfigSet/*[1]"!]
[!LOOP "CanController/*"!]
[!VAR "HWChannel" = "CanHwChannel"!]
[!LOOP "CanControllerBaudrateConfig/*"!][!CODE!]
#define CAN_CFGSET0_BAUDRATE_FC_[!"substring-after($HWChannel,'FlexCAN_')"!]_[!"@index"!]         [!"CanControllerBaudRate"!]U[!ENDCODE!][!ENDLOOP!][!CODE!]
#define CAN_CFGSET0_MAX_BAUDRATE_FC_[!"substring-after($HWChannel,'FlexCAN_')"!]_[!"@index"!]         [!"num:i(count(CanControllerBaudrateConfig/*))"!]U
[!ENDCODE!][!ENDLOOP!][!ENDSELECT!]
[!ELSE!]
[!LOOP "CanConfigSet/*"!]
[!VAR "CSET_NR" = "@index"!]
[!LOOP "CanController/*"!]
[!VAR "HWChannel" = "CanHwChannel"!]
[!LOOP "CanControllerBaudrateConfig/*"!][!CODE!]
#define CAN_CFGSET[!"num:i($CSET_NR)"!]_BAUDRATE_FC_[!"substring-after($HWChannel,'FlexCAN_')"!]_[!"@index"!]        [!"CanControllerBaudRate"!]U[!ENDCODE!][!ENDLOOP!][!CODE!]
#define CAN_CFGSET[!"num:i($CSET_NR)"!]_MAX_BAUDRATE_FC_[!"substring-after($HWChannel,'FlexCAN_')"!]_[!"@index"!]         [!"num:i(count(CanControllerBaudrateConfig/*))"!]U
[!ENDCODE!][!ENDLOOP!][!ENDLOOP!][!ENDIF!][!ENDNOCODE!]

/*
* @brief          Maximum number of Filters configured for RxFifo.
* @details        Maximum number of Filters configured for RxFifo.
*
* @implements     DCAN02629
*/[!NOCODE!][!LOOP "CanConfigSet/*"!][!VAR "TableIdCount" = "0"!]
[!LOOP "CanController/*"!][!IF "CanControllerRxFifoEnable = 'true'"!][!VAR "TableIdCount" = "$TableIdCount+8"!][!ENDIF!][!ENDLOOP!]
[!IF "$TableIdCount != 0"!][!CODE!]
#define CAN_MAXTABLEID_[!"@index"!] [!"num:i($TableIdCount)"!]U[!ENDCODE!][!ENDIF!][!ENDLOOP!][!ENDNOCODE!]

[!VAR "rxfifoenable" = "0"!][!LOOP "CanConfigSet/*/CanController/*"!][!IF "CanControllerRxFifoEnable = 'true'"!][!VAR "rxfifoenable" = "1"!][!ENDIF!][!ENDLOOP!]
/*
* @brief          Support for Rx Fifo
* @details        Support for Rx Fifo - If at least one controller supports RxFifo, then this define is set to STD_ON.
*                 This define is global for the entire hardware unit (all controllers). Every controller has particular
*                 configuration for Rx Fifo (see Can_ControllerConfigType structure).
*
* @implements     DCAN02630
*/
#define CAN_RXFIFO_ENABLE [!IF "$rxfifoenable = 1"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]

/*
* @brief          Set if Rx Fifo events (Warning/Overflow/FrameAvailable) are configured on the same int on INTC vector table.
* @details        Set if Rx Fifo events (Warning/Overflow/FrameAvailable) are configured on the same int on INTC vector table.
*                 Based on this define separate interrupts handlers or not will be used for the 3 events of the RxFifo.
*
* @implements     DCAN02631
*/
#define CAN_RXFIFO_EVENT_UNIFIED [!IF "ecu:get('Can.CanConfigSet.RxFifoEventsUnified')='STD_ON'"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]

/*
* @brief          Error notification enabled/disabled.
* @details        Enables/Disables the Error Controller Notification. Used for Interrupts mapping in Can_Irq.c file.
*
* @implements     DCAN02659
*/
#define CAN_ERROR_NOTIFICATION_ENABLE [!IF "CanConfigSet/*/CanController/*/CanErrorControllerNotifEn = 'true'"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]

[!SELECT "CanConfigSet/*[1]"!][!LOOP "CanController/*"!]
[!IF "CanHwChannel = 'FlexCAN_A'"!]
/*
* @brief          Index into the configuration structures.
* @details        Index into the configuration structures.Indexes used for accessing the 'Can_ControlerDescriptorType' structure.
*                 NOTE that index order from hardware (where CAN_A has always index 0, ..)
*                 may not be the same with the order from the 'Can_ControlerDescriptorType' structure (where user can define controllers in any order).
*                 Count also the number of controllers that have interrupts enabled.
*
* @implements     DCAN02632
*/
#define CAN_FCA_INDEX       ((uint8)[!"num:i(CanControllerId)"!]U)

/*
* @brief          Index into the hardware platform.
* @details        Index into the hardware platform.Indexes used for accessing the 'Can_ControlerDescriptorType' structure.
*
* @implements     DCAN02633
*/
#define FLEXCAN_A_OFFSET    ((uint8)0U)

/*
* @brief          RxFifo Functionality enabled/disabled. Used for Interrupts mapping in Can_Irq.c file.
* @details        RxFifo Functionality enabled/disabled. Used for Interrupts mapping in Can_Irq.c file.
*
* @implements     DCAN02634
*/
#define CAN_A_FIFO_EN       [!IF "CanControllerRxFifoEnable = 'true'"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]

/*
* @brief          Error notification enabled/disabled.
* @details        Enables/Disables the Error Controller Notification. Used for Interrupts mapping in Can_Irq.c file.
*
* @implements     DCAN02658
*/
#define CAN_A_ERROR_NOTIFICATION_ENABLE  [!IF "CanErrorControllerNotifEn = 'true'"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]
[!ELSEIF "CanHwChannel = 'FlexCAN_B'"!]
/*
* @brief          Index into the configuration structures.
* @details        Index into the configuration structures.
*
* @implements     DCAN02632
*/
#define CAN_FCB_INDEX       ((uint8)[!"num:i(CanControllerId)"!]U)


/*
* @brief          Index into the hardware platform.
* @details        Index into the hardware platform.
*
* @implements     DCAN02633
*/
#define FLEXCAN_B_OFFSET    ((uint8)1U)
/*
* @brief          RxFifo Functionality enabled/disabled. Used for Interrupts mapping in Can_Irq.c file.
* @details        RxFifo Functionality enabled/disabled. Used for Interrupts mapping in Can_Irq.c file.
*
* @implements     DCAN02634
*/
#define CAN_B_FIFO_EN       [!IF "CanControllerRxFifoEnable = 'true'"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]

/*
* @brief          Error notification enabled/disabled.
* @details        Enables/Disables the Error Controller Notification. Used for Interrupts mapping in Can_Irq.c file.
*
* @implements     DCAN02658
*/
#define CAN_B_ERROR_NOTIFICATION_ENABLE  [!IF "CanErrorControllerNotifEn = 'true'"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]
[!ELSEIF "CanHwChannel = 'FlexCAN_C'"!]
/*
* @brief          Index into the configuration structures
* @details        Index into the configuration structures
*
* @implements     DCAN02632
*/
#define CAN_FCC_INDEX       ((uint8)[!"num:i(CanControllerId)"!]U)


/*
* @brief          Index into the hardware platform.
* @details        Index into the hardware platform.
*
* @implements     DCAN02633
*/
#define FLEXCAN_C_OFFSET    ((uint8)2U)
/*
* @brief          RxFifo Functionality enabled/disabled. Used for Interrupts mapping in Can_Irq.c file.
* @details        RxFifo Functionality enabled/disabled. Used for Interrupts mapping in Can_Irq.c file.
*
* @implements     DCAN02634
*/
#define CAN_C_FIFO_EN       [!IF "CanControllerRxFifoEnable = 'true'"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]

/*
* @brief          Error notification enabled/disabled.
* @details        Enables/Disables the Error Controller Notification. Used for Interrupts mapping in Can_Irq.c file.
*
* @implements     DCAN02658
*/
#define CAN_C_ERROR_NOTIFICATION_ENABLE  [!IF "CanErrorControllerNotifEn = 'true'"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]
[!ELSEIF "CanHwChannel = 'FlexCAN_D'"!]
/*
* @brief          Index into the configuration structures.
* @details        Index into the configuration structures.
*
* @implements     DCAN02632
*/
#define CAN_FCD_INDEX       ((uint8)[!"num:i(CanControllerId)"!]U)


/*
* @brief          Index into the hardware platform.
* @details        Index into the hardware platform.
*
* @implements     DCAN02633
*/
#define FLEXCAN_D_OFFSET    ((uint8)3U)
/*
* @brief          RxFifo Functionality enabled/disabled. Used for Interrupts mapping in Can_Irq.c file.
* @details        RxFifo Functionality enabled/disabled. Used for Interrupts mapping in Can_Irq.c file.
*
* @implements     DCAN02634
*/
#define CAN_D_FIFO_EN       [!IF "CanControllerRxFifoEnable = 'true'"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]

/*
* @brief          Error notification enabled/disabled.
* @details        Enables/Disables the Error Controller Notification. Used for Interrupts mapping in Can_Irq.c file.
*
* @implements     DCAN02658
*/
#define CAN_D_ERROR_NOTIFICATION_ENABLE  [!IF "CanErrorControllerNotifEn = 'true'"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]
[!ELSEIF "CanHwChannel = 'FlexCAN_E'"!]
/*
* @brief          Index into the configuration structures.
* @details        Index into the configuration structures.
*
* @implements     DCAN02632
*/
#define CAN_FCE_INDEX       ((uint8)[!"num:i(CanControllerId)"!]U)


/*
* @brief          Index into the hardware platform.
* @details        Index into the hardware platform.
*
* @implements     DCAN02633
*/
#define FLEXCAN_E_OFFSET    ((uint8)4U)
/*
* @brief          RxFifo Functionality enabled/disabled. Used for Interrupts mapping in Can_Irq.c file.
* @details        RxFifo Functionality enabled/disabled. Used for Interrupts mapping in Can_Irq.c file.
*
* @implements     DCAN02634
*/
#define CAN_E_FIFO_EN       [!IF "CanControllerRxFifoEnable = 'true'"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]

/*
* @brief          Error notification enabled/disabled.
* @details        Enables/Disables the Error Controller Notification. Used for Interrupts mapping in Can_Irq.c file.
*
* @implements     DCAN02658
*/
#define CAN_E_ERROR_NOTIFICATION_ENABLE  [!IF "CanErrorControllerNotifEn = 'true'"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]
[!ELSEIF "CanHwChannel = 'FlexCAN_F'"!]
/*
* @brief          Index into the configuration structures.
* @details        Index into the configuration structures.
*
* @implements     DCAN02632
*/
#define CAN_FCF_INDEX       ((uint8)[!"num:i(CanControllerId)"!]U)


/*
* @brief          Index into the hardware platform.
* @details        Index into the hardware platform.
*
* @implements     DCAN02633
*/
#define FLEXCAN_F_OFFSET    ((uint8)5U)
/*
* @brief          RxFifo Functionality enabled/disabled. Used for Interrupts mapping in Can_Irq.c file.
* @details        RxFifo Functionality enabled/disabled. Used for Interrupts mapping in Can_Irq.c file.
*
* @implements     DCAN02634
*/
#define CAN_F_FIFO_EN       [!IF "CanControllerRxFifoEnable = 'true'"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]

/*
* @brief          Error notification enabled/disabled.
* @details        Enables/Disables the Error Controller Notification. Used for Interrupts mapping in Can_Irq.c file.
*
* @implements     DCAN02658
*/
#define CAN_F_ERROR_NOTIFICATION_ENABLE  [!IF "CanErrorControllerNotifEn = 'true'"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]
[!ELSEIF "CanHwChannel = 'FlexCAN_G'"!]
/*
* @brief          Index into the configuration structures.
* @details        Index into the configuration structures.
*
* @implements     DCAN02632
*/
#define CAN_FCG_INDEX       ((uint8)[!"num:i(CanControllerId)"!]U)


/*
* @brief          Index into the hardware platform.
* @details        Index into the hardware platform.
*
* @implements     DCAN02633
*/
#define FLEXCAN_G_OFFSET    ((uint8)6U)
/*
* @brief          RxFifo Functionality enabled/disabled. Used for Interrupts mapping in Can_Irq.c file.
* @details        RxFifo Functionality enabled/disabled. Used for Interrupts mapping in Can_Irq.c file.
*
* @implements     DCAN02634
*/
#define CAN_G_FIFO_EN       [!IF "CanControllerRxFifoEnable = 'true'"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]

/*
* @brief          Error notification enabled/disabled.
* @details        Enables/Disables the Error Controller Notification. Used for Interrupts mapping in Can_Irq.c file.
*
* @implements     DCAN02658
*/
#define CAN_G_ERROR_NOTIFICATION_ENABLE  [!IF "CanErrorControllerNotifEn = 'true'"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]
[!ELSEIF "CanHwChannel = 'FlexCAN_H'"!]
/*
* @brief          Index into the configuration structures.
* @details        Index into the configuration structures.
*
* @implements     DCAN02632
*/
#define CAN_FCH_INDEX       ((uint8)[!"num:i(CanControllerId)"!]U)


/*
* @brief          Index into the hardware platform.
* @details        Index into the hardware platform.
*
* @implements     DCAN02633
*/
#define FLEXCAN_H_OFFSET    ((uint8)7U)
/*
* @brief          RxFifo Functionality enabled/disabled. Used for Interrupts mapping in Can_Irq.c file.
* @details        RxFifo Functionality enabled/disabled. Used for Interrupts mapping in Can_Irq.c file.
*
* @implements     DCAN02634
*/
#define CAN_H_FIFO_EN       [!IF "CanControllerRxFifoEnable = 'true'"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]

/*
* @brief          Error notification enabled/disabled.
* @details        Enables/Disables the Error Controller Notification. Used for Interrupts mapping in Can_Irq.c file.
*
* @implements     DCAN02658
*/
#define CAN_H_ERROR_NOTIFICATION_ENABLE  [!IF "CanErrorControllerNotifEn = 'true'"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]
[!ENDIF!][!ENDLOOP!][!ENDSELECT!]

#if (CAN_API_ERROR_STATUS == STD_ON)
/*
@brief    Macro used to define the NoAck Error   .
*/
#define CAN_NO_ACK_ERR  ((uint32)0x00U)
#endif

/*
* @brief          Optimization of interrupt service code for size.
* @details        Optimization of interrupt service code for size.
*
* @implements     DCAN02635
*/
#define CAN_ISROPTCODESIZE [!IF "CanGeneral/CanCodeSizeOptimization = 'true'"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]

/*
* @brief          Enable Non-Autosar API for Dual-Clock support.
* @details        Enable Non-Autosar API for Dual-Clock support.
*                 This can be set to STD_ON only if it is activated from Resource file (Can.CanConfig.DualClockMode = STD_ON)
*
* @implements     DCAN02636
*/
#define CAN_DUAL_CLOCK_MODE [!IF "ecu:get('Can.CanConfig.DualClockMode')='STD_ON'"!][!IF "CanGeneral/CanEnableDualClockMode = 'true'"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!][!ELSE!](STD_OFF)[!ENDIF!]

/*
* @brief          (CAN113_Conf) Specifies the maximum time for blocking function until a timeout is detected. Unit in loops.
* @details        (CAN281) The Can module shall use the free running timer provided by the system service for timeout detection in case the hardware does not react
*                  in the expected time (hardware malfunction) to prevent endless loops.
*
* @implements     DCAN02048, DCAN01076, DCAN02637
*/

#if defined(ERR_IPV_FLEXCAN_0008)
    #if (ERR_IPV_FLEXCAN_0008 == STD_ON)
        #define CAN_TIMEOUT_DURATION 50000U
    #else
        #error: The define ERR_IPV_FLEXCAN_0008 should not be STD_OFF
    #endif
#else
    #define CAN_TIMEOUT_DURATION [!SELECT "CanGeneral"!][!"num:i(CanTimeoutDuration)"!]U[!ENDSELECT!]
#endif /* ERR_IPV_FLEXCAN_0008 */

/**
* @brief   Switches the Production Error Detection and Notification OFF
*
* @api
*/
[!NOCODE!][!//
[!VAR "CanDemErrorEnable" = "'false'"!][!//
[!IF "NonAutosar/CanDisableDemReportErrorStatus ='false'"!][!//
    [!VAR "nconf" = "count(CanConfigSet/*)"!][!//
    [!VAR "iconf" = "0"!][!//
    [!FOR "iconf" = "1" TO "$nconf"!][!//
        [!IF "node:exists(CanConfigSet/*[$iconf]/CanDemEventParameterRefs)"!][!//
            [!VAR "CanDemErrorEnable" = "'true'"!][!//
        [!ENDIF!][!//
    [!ENDFOR!][!//
[!ENDIF!][!//
[!ENDNOCODE!][!//
/*
* @violates @ref Can_Cfg_h_REF_6 C macros shall only expand to a braced initialiser, a constant, a parenthesised expression 
* @violates @ref Can_Cfg_h_REF_7 Identifiers (internal and external) shall not rely on the significance of more than 31
* characters.
*/
#define CAN_DISABLE_DEM_REPORT_ERROR_STATUS   [!IF "$CanDemErrorEnable"!]STD_ON  /* Enable Production Error Detection */[!ELSE!]STD_OFF /* Disable Production Error Detection */[!ENDIF!]

[!IF "IMPLEMENTATION_CONFIG_VARIANT = 'VariantPreCompile'"!]
/*
* @brief          Precompile Support On.
* @details        (CAN220)VARIANT-PRE-COMPILE: Only pre-compile configuration parameters
*
* @implements     DCAN02638
*/
#define CAN_PRECOMPILE_SUPPORT (STD_ON)
[!ELSE!]
#define CAN_PRECOMPILE_SUPPORT (STD_OFF)

[!ENDIF!]

/**
* @brief          Export Can_ConfigType structure.
* @details        Export Can_ConfigType structure. This is the type of the external data structure containing
*                 the overall initialization data for the CAN driver and affecting all controllers.
*
* @implements     DCAN02639
*/
[!IF "IMPLEMENTATION_CONFIG_VARIANT='VariantPostBuild'"!]
#if (CAN_PRECOMPILE_SUPPORT == STD_OFF)
[!NOCODE!][!VAR "var_count1"="num:i(count(CanConfigSet/*))"!][!VAR "w"="0"!][!ENDNOCODE!]
  /* Export Driver configuration */
  /* @violates @ref Can_Cfg_h_REF_4 C macros shall only expand to a braced initialiser,  a constant, a parenthesised expression */
  #define CAN_INIT_CONFIG_PB_DEFINES \[!LOOP "CanConfigSet/*"!][!VAR "w"="$w + 1"!]
    extern CONST(Can_ConfigType, CAN_CONST) [!"node:name(.)"!]; [!IF "$w < $var_count1"!] \[!ENDIF!][!ENDLOOP!]

#endif
[!ELSE!]
#if (CAN_PRECOMPILE_SUPPORT == STD_ON)
  /* Export Driver configuration */
 /* @violates @ref Can_Cfg_h_REF_4 C macros shall only expand to a braced initialiser,  a constant, a parenthesised expression */
  #define CAN_INIT_CONFIG_PC_DEFINES \
    extern CONST(Can_ConfigType, CAN_CONST) Can_ConfigSet_PC;

  #define [!"node:name(CanConfigSet/*[1])"!]  (Can_ConfigSet_PC)

#endif
[!ENDIF!]

[!IF "node:exists(CanGeneral/CanMainFunctionBusoffPeriod)"!]
/*
* @brief          Periods for cyclic call of Main function
* @details        (CAN355_Conf) CanMainFunctionBusoffPeriod - This parameter describes the period for cyclic call to Can_MainFunction_Busoff. Unit is seconds.
*
* @implements     DCAN02038
*/
#define CAN_MAINFUNCTION_PERIOD_BUSOFF  ([!SELECT "CanGeneral"!][!"num:i(CanMainFunctionBusoffPeriod)"!]U[!ENDSELECT!])
[!ENDIF!]

#if (CAN_RXPOLL_SUPPORTED == STD_ON)
[!IF "node:exists(CanGeneral/CanMainFunctionRWPeriods/*/CanMainFunctionReadPeriod)"!][!//
[!IF "num:i(count(CanGeneral/CanMainFunctionRWPeriods/*/CanMainFunctionReadPeriod/*)) > 0"!][!//
/*
* @brief          Periods for cyclic call of Main function
* @details        (CAN356_Conf) CanMainFunctionReadPeriod - This parameter describes the period for cyclic call to Can_MainFunction_Read. Unit is seconds.
*
* @implements     DCAN02039
*/
[!IF "num:i(count(CanGeneral/CanMainFunctionRWPeriods/*/CanMainFunctionReadPeriod/*)) > 1"!][!//
[!LOOP "CanGeneral/CanMainFunctionRWPeriods/*"!][!//
[!IF "node:exists(CanMainFunctionReadPeriod/*/CanMainFunctionReadPeriod)"!][!//
#define CAN_MAINFUNCTION_PERIOD_READ_[!"@index"!]       ([!"./CanMainFunctionReadPeriod/*/CanMainFunctionReadPeriod"!]U)
/* @violates @ref Can_Cfg_h_REF_2 Violates MISRA 2004 Advisory Rule 19.7, Function-like macro defined. */
#define Can_MainFunction_Read_[!"@index"!]()    (Can_LLD_MainFunction_Multiple_Read_Poll([!"@index"!]))
[!ENDIF!]
[!ENDLOOP!][!//
[!ELSE!][!//
[!IF "num:i(count(CanGeneral/CanMainFunctionRWPeriods/*/CanMainFunctionReadPeriod/*)) != 0"!][!//
[!LOOP "CanGeneral/CanMainFunctionRWPeriods/*"!][!//
[!IF "node:exists(CanMainFunctionReadPeriod/*[1]/CanMainFunctionReadPeriod)"!][!//
#define CAN_MAINFUNCTION_PERIOD_READ    ([!"CanMainFunctionReadPeriod/*[1]/CanMainFunctionReadPeriod"!]U)
[!ENDIF!][!//
[!ENDLOOP!][!//
[!ENDIF!][!ENDIF!][!ENDIF!][!ENDIF!]
#endif /* (CAN_RXPOLL_SUPPORTED == STD_OFF) */

[!IF "node:exists(CanGeneral/CanMainFunctionWakeupPeriod)"!]
/*
* @brief          Periods for cyclic call of Main function
* @details        (CAN357_Conf) CanMainFunctionWakeupPeriod - This parameter describes the period for cyclic call to Can_MainFunction_Wakeup. Unit is seconds.
*
* @implements     DCAN02040
*/
#define CAN_MAINFUNCTION_PERIOD_WAKEUP  [!SELECT "CanGeneral"!][!"num:i(CanMainFunctionWakeupPeriod)"!]U[!ENDSELECT!]
[!ENDIF!]

#if (CAN_TXPOLL_SUPPORTED == STD_ON)
[!IF "node:exists(CanGeneral/CanMainFunctionRWPeriods/*/CanMainFunctionWritePeriod)"!][!//
[!IF "num:i(count(CanGeneral/CanMainFunctionRWPeriods/*/CanMainFunctionWritePeriod/*)) > 0"!][!//
/*
* @brief          Periods for cyclic call of Main function Write
* @details        (CAN358_Conf) CanMainFunctionWritePeriod - This parameter describes the period for cyclic call to Can_MainFunction_Write. Unit is seconds.
*
* @implements     DCAN02041
*/
[!IF "num:i(count(CanGeneral/CanMainFunctionRWPeriods/*/CanMainFunctionWritePeriod/*)) > 1"!][!//
[!LOOP "CanGeneral/CanMainFunctionRWPeriods/*"!][!//
[!IF "node:exists(./CanMainFunctionWritePeriod/*/CanMainFunctionWritePeriod)"!][!//
#define CAN_MAINFUNCTION_PERIOD_WRITE_[!"@index"!]      ([!"./CanMainFunctionWritePeriod/*/CanMainFunctionWritePeriod"!]U)
/* @violates @ref Can_Cfg_h_REF_2 Violates MISRA 2004 Advisory Rule 19.7, Function-like macro defined. */
#define Can_MainFunction_Write_[!"@index"!]()    (Can_LLD_MainFunction_Multiple_Write_Poll([!"@index"!]))
[!ENDIF!]
[!ENDLOOP!][!//
[!ELSE!][!//
[!IF "num:i(count(CanGeneral/CanMainFunctionRWPeriods/*/CanMainFunctionWritePeriod/*)) != 0"!][!//
[!LOOP "CanGeneral/CanMainFunctionRWPeriods/*"!][!//
[!IF "node:exists(CanMainFunctionWritePeriod/*[1]/CanMainFunctionWritePeriod)"!][!//
#define CAN_MAINFUNCTION_PERIOD_WRITE    ([!"CanMainFunctionWritePeriod/*[1]/CanMainFunctionWritePeriod"!]U)
[!ENDIF!][!//
[!ENDLOOP!][!//
[!ENDIF!][!ENDIF!][!ENDIF!][!ENDIF!]
#endif /* (CAN_TXPOLL_SUPPORTED == STD_OFF) */

/*
* @brief          Periods for cyclic call of Main function Mode
* @details        (CAN376_Conf) This parameter describes the period for cyclic call to Can_MainFunction_Mode. Unit is seconds.
*
* @implements     DCAN02042
*/
#define CAN_MAINFUNCTION_MODE_PERIOD   ([!SELECT "CanGeneral"!][!"num:i(CanMainFunctionModePeriod)"!]U[!ENDSELECT!])

[!VAR "BccSupport" = "0"!][!LOOP "CanConfigSet/*/CanController/*"!][!IF "CanBccSupport = 'true'"!][!VAR "BccSupport" = "1"!][!ENDIF!][!ENDLOOP!]
/*
* @brief    Defines if Backwards Compatibility Configuration (BCC) feature of CAN controller is used in the configuration.
*           If BCC feature of CAN controller is enabled, Individual Rx masking and queue feature are disabled.
*           If BCC feature of CAN controller is disabled, Individual Rx masking and queue feature are enabled.
*/
#define CAN_BCC_SUPPORT_ENABLE [!IF "$BccSupport = 1"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]

[!NOCODE!]
[!VAR "Can_hardware_ob_id" = "0"!]
[!LOOP "CanConfigSet/*/CanHardwareObject/*"!]
[!IF "$Can_hardware_ob_id < CanObjectId"!]
[!VAR "Can_hardware_ob_id" = "CanObjectId"!]
[!ENDIF!]
[!ENDLOOP!][!ENDNOCODE!]
/*
@brief    Macro used to define the maximum of Can object IDs configured  .
*/
#define CAN_MAX_OBJECT_ID ((uint32)[!"num:i($Can_hardware_ob_id + 1)"!]U)
/*==================================================================================================
*                                      DEFINES AND MACROS
==================================================================================================*/

/* @violates @ref Can_Cfg_h_REF_5 This is required as per autosar Requirement. */
#define CAN_LPDU_NOTIFICATION_ENABLE [!IF "node:exists(CanGeneral/CanLPduReceiveCalloutFunction)"!][!IF "(normalize-space(CanLPduReceiveCalloutFunction) != 'NULL_PTR') and (normalize-space(CanLPduReceiveCalloutFunction) != 'NULL') and (normalize-space(CanGeneral/CanLPduReceiveCalloutFunction) != 'Null') and (normalize-space(CanGeneral/CanLPduReceiveCalloutFunction) != 'null')"!] (STD_ON)[!ELSE!](STD_OFF)[!ENDIF!][!ELSE!](STD_OFF)[!ENDIF!]

/*==================================================================================================
*                                             ENUMS
==================================================================================================*/

/*==================================================================================================
*                                STRUCTURES AND OTHER TYPEDEFS
==================================================================================================*/

/*==================================================================================================
*                                GLOBAL VARIABLE DECLARATIONS
==================================================================================================*/

/*==================================================================================================
*                                    FUNCTION PROTOTYPES
==================================================================================================*/
[!IF "node:exists(CanGeneral/CanLPduReceiveCalloutFunction)"!]
[!SELECT "CanGeneral"!][!IF "(normalize-space(CanLPduReceiveCalloutFunction) != 'NULL_PTR') and (normalize-space(CanLPduReceiveCalloutFunction) != 'NULL') and (normalize-space(CanLPduReceiveCalloutFunction) != 'Null') and (normalize-space(CanLPduReceiveCalloutFunction) != 'null')"!]
/*
@brief    This inclusion shall be made here, after the definition of other defines  which are used by the included file.
*/
#include "ComStack_Types.h"
#include "Can_GeneralTypes.h"

extern FUNC(boolean, COM_APPL_CODE) [!"normalize-space(CanLPduReceiveCalloutFunction)"!](uint8 Hrh,Can_IdType CanId,uint8 CanDlc,const uint8 *CanSduPtr);
/** @violates @ref Can_Cfg_h_REF_2 Violates MISRA 2004 Advisory Rule 19.7, Function-like macro defined.*/
#define CanLPduReceiveCalloutFunction(Hrh, CanId, CanDlc, CanSduPtr)     [!"normalize-space(CanLPduReceiveCalloutFunction)"!]((Hrh),(CanId),(CanDlc),(CanSduPtr))
[!ENDIF!][!ENDSELECT!][!ENDIF!]

#ifdef __cplusplus
}
#endif

#endif /* _CAN_CFG_H_ */

/** @} */
