[!CODE!][!//
/**
*   @file    Dio_Cfg.c
*   @version 1.0.1
*
*   @brief   AUTOSAR Dio precompile configuration code.
*   @details This file is the Autosar DIO driver precompile configuration
*            code. This file is automatically generated, do not modify manually.
*
*   @addtogroup DIO_CFG
*   @{
*/
/*==================================================================================================
*   Project              : AUTOSAR 4.0 MCAL
*   Platform             : PA
*   Peripheral           : SIUL
*   Dependencies         : none
*
*   Autosar Version      : 4.0.3
*   Autosar Revision     : ASR_REL_4_0_REV_0003
*   Autosar Conf.Variant :
*   SW Version           : 1.0.1
*   Build Version        : MPC560xB_MCAL_1_0_1_RTM_ASR_REL_4_0_REV_0003_20140606
*
*   (c) Copyright 2006-2014 Freescale Semiconductor Inc and STMicroelectronics
*   All Rights Reserved.
==================================================================================================*/
/*==================================================================================================
==================================================================================================*/

/**
* @page misra_violations MISRA-C:2004 violations
*
* @section Dio_CFG_REF_1
* Violates MISRA 2004 Advisory Rule 19.1, only preprocessor statements and comments before "#include"
* This violation is not fixed since the inclusion of MemMap.h is as per Autosar requirement.

*
* @section Dio_CFG_REF_2
* Violates MISRA 2004 Required Rule 19.15, Repeated include file
* This comes from the order of includes in the .c file and from include dependencies. As a safe
* approach, any file must include all its dependencies. Header files are already protected against
* double inclusions.
*
* @section Dio_CFG_REF_3
* Violates MISRA 2004 Required Rule 1.4, The compiler/linker shall be checked to ensure that 
* 31 character signifiance and case sensitivity are supported for external identifiers.
*
* @section Dio_CFG_REF_4
* Violates MISRA 2004 Required Rule 8.10, All declarations and definitions of objects or 
* functions at file scope shall have internal linkage unless external linkage is required.
* State variables may be used by LLD layer.
*
* @section Dio_CFG_REF_5
* Violates MISRA 2004 Required Rule 5.1,
* Identifiers (internal and external) shall not rely on the significance of more than 31
* characters.
*/

#ifdef __cplusplus
extern "C" {
#endif


/*==================================================================================================
*                                        INCLUDE FILES
* 1) system and project includes
* 2) needed interfaces from external units
* 3) internal and external interfaces from this unit
==================================================================================================*/

#include "Dio.h"
#if defined(DIO_PRECOMPILE_SUPPORT) || defined(__DOXYGEN__)
/*==================================================================================================
*                              SOURCE FILE VERSION INFORMATION
==================================================================================================*/

#define DIO_VENDOR_ID_CFG_C                   43
/*
* @violates @ref Dio_CFG_REF_3 The compiler/linker shall be checked to ensure that 31 character
* signifiance and case sensitivity are supported for external identifiers
*/
/*
* @violates @ref Dio_CFG_REF_5 Identifiers (internal and external) shall not rely on the significance of more than 31
* characters.
*/
#define DIO_AR_RELEASE_MAJOR_VERSION_CFG_C    4
/*
* @violates @ref Dio_CFG_REF_3 The compiler/linker shall be checked to ensure that 31 character
* signifiance and case sensitivity are supported for external identifiers
*/
/*
* @violates @ref Dio_CFG_REF_5 Identifiers (internal and external) shall not rely on the significance of more than 31
* characters.
*/
#define DIO_AR_RELEASE_MINOR_VERSION_CFG_C    0
/*
* @violates @ref Dio_CFG_REF_3 The compiler/linker shall be checked to ensure that 31 character
* signifiance and case sensitivity are supported for external identifiers
*/
/*
* @violates @ref Dio_CFG_REF_5 Identifiers (internal and external) shall not rely on the significance of more than 31
* characters.
*/
#define DIO_AR_RELEASE_REVISION_VERSION_CFG_C 3
#define DIO_SW_MAJOR_VERSION_CFG_C            1
#define DIO_SW_MINOR_VERSION_CFG_C            0
#define DIO_SW_PATCH_VERSION_CFG_C            1

/*==================================================================================================
*                                     FILE VERSION CHECKS
==================================================================================================*/

/* @implements DDIO04013.*/
#if (((DIO_AR_RELEASE_MAJOR_VERSION_CFG_C != DIO_AR_RELEASE_MAJOR_VERSION) || \
      (DIO_AR_RELEASE_MINOR_VERSION_CFG_C != DIO_AR_RELEASE_MINOR_VERSION)) || \
      (DIO_AR_RELEASE_REVISION_VERSION_CFG_C != DIO_AR_RELEASE_REVISION_VERSION))
      #error "AutoSar Version Numbers of Dio_Cfg.c and Dio.h are different"
#endif
#if  ((DIO_SW_MAJOR_VERSION_CFG_C != DIO_SW_MAJOR_VERSION) || \
      (DIO_SW_MINOR_VERSION_CFG_C != DIO_SW_MINOR_VERSION) || \
      (DIO_SW_PATCH_VERSION_CFG_C != DIO_SW_PATCH_VERSION))
      #error "Software Version Numbers of Dio_Cfg.c and Dio.h are different"
#endif
#if ((DIO_VENDOR_ID_CFG_C != DIO_VENDOR_ID))
    #error "VENDOR ID for Dio_Cfg.h and Dio.h is different"
#endif

/*==================================================================================================
*                          LOCAL TYPEDEFS (STRUCTURES, UNIONS, ENUMS)
==================================================================================================*/


/*==================================================================================================
*                                       LOCAL MACROS
==================================================================================================*/


/*==================================================================================================
*                                      LOCAL CONSTANTS
==================================================================================================*/


/*==================================================================================================
*                                      LOCAL VARIABLES
==================================================================================================*/


/*==================================================================================================
*                                      GLOBAL CONSTANTS
==================================================================================================*/

/*
* @violates @ref Dio_CFG_REF_5 Identifiers (internal and external) shall not rely on the significance of more than 31
* characters.
*/
#define DIO_START_SEC_CONFIG_DATA_UNSPECIFIED
/** @violates @ref Dio_CFG_REF_1
    MISRA 2004 Advisory Rule 19.1, only preprocessor statements and comments
    before '#include'.*/
/**
* @violates @ref Dio_CFG_REF_2 Precautions shall be taken in order to prevent
* the contents of a header file being included twice
*/
#include "MemMap.h"

[!IF "DioGeneral/DioDevErrorDetect"!][!//
/**
* @brief          Pin intervals representation.
* @details        This is an array containing valid pin intervals, intervals
*                 are closed.
*
* @api
*/
CONST(Dio_ChannelType, DIO_CONST) valid_pin_ranges[DIO_PIN_INTERVALS] = {
    (Dio_ChannelType)[!"text:replaceAll(ecu:get('Dio.AvailablePins'),',',', (Dio_ChannelType)')"!]
};[!//
[!ENDIF!]

[!IF "DioGeneral/DioDevErrorDetect"!][!//
/**
* @brief          Port intervals representation.
* @details        This is an array containing valid port intervals, intervals
*                 are closed.
*
* @api
*/
CONST(Dio_PortType, DIO_CONST) valid_port_ranges[DIO_PORT_INTERVALS] = {
    (Dio_PortType)[!"text:replaceAll(ecu:get('Dio.AvailablePorts'),',',', (Dio_PortType)')"!]
};[!//
[!ENDIF!][!//

[!IF "DioGeneral/DioReadZeroForUndefinedPortPins"!]
[!VAR "pin_list"="ecu:get('Dio.AvailablePins')"!][!//
[!VAR "crt_mask" = "num:i(0)"!][!//
[!VAR "crt_interval_min" = "substring-before($pin_list,',')"!][!//
[!VAR "pin_list" = "substring-after($pin_list, ',')"!][!//
[!IF "substring-after($pin_list, ',') = ''"!][!//
[!VAR "crt_interval_max" = "substring-after(ecu:get('Dio.AvailablePins'),',')"!][!//
[!ELSE!][!//
[!VAR "crt_interval_max" = "substring-before($pin_list,',')"!][!//
[!ENDIF!][!//
[!VAR "pin_list" = "substring-after($pin_list, ',')"!][!//
/**
* @brief          Undefined pins mask representation.
* @details        This is an array of masks to set undefined port pins as zero.
*/
CONST(Dio_PortLevelType, DIO_CONST) undefined_portmask[DIO_AVAILABLE_PORTS] = {
[!FOR "crt_pin" = "num:i(0)" TO "16*(num:i(number(substring-before(substring-after(ecu:list('Dio.AvailablePorts'),','),']')))+1)-1"!][!//
[!IF "$crt_pin > $crt_interval_max and $crt_interval_max != ''"!][!//
[!VAR "crt_interval_min" = "substring-before($pin_list,',')"!][!//
[!VAR "pin_list" = "substring-after($pin_list, ',')"!][!//
[!VAR "crt_interval_max" = "substring-before($pin_list, ',')"!][!//
[!IF "$crt_interval_max = ''"!][!//
[!VAR "crt_interval_max" = "$pin_list"!][!//
[!ENDIF!][!//
[!VAR "pin_list" = "substring-after($pin_list, ',')"!][!//
[!ENDIF!][!//
[!IF "$crt_pin < $crt_interval_min or $crt_interval_min = ''"!][!//
[!VAR "crt_mask" = "bit:or($crt_mask, bit:shl(0, (15-num:i($crt_pin mod 16))))"!][!//
[!ELSE!][!//
[!VAR "crt_mask" = "bit:or($crt_mask, bit:shl(1, (15-num:i($crt_pin mod 16))))"!][!//
[!ENDIF!][!//
[!IF "(($crt_pin+1) mod 16) = 0"!][!//
    (Dio_PortLevelType)[!"num:inttohex($crt_mask, 4)"!][!//
[!IF "$crt_pin < 16*(num:i(number(substring-before(substring-after(ecu:list('Dio.AvailablePorts'),','),']')))+1)-1"!],[!ENDIF!]
[!VAR "crt_mask" = "num:i(0)"!][!//
[!ENDIF!][!//
[!ENDFOR!][!//
};
[!ENDIF!][!//
[!//
[!MACRO "reverse_bits"!][!//
[!NOCODE!]
    [!VAR "Orig_mask"="DioPortMask"!]
    [!VAR "Orig_offset"="DioPortOffset"!]
    [!IF "../../../../DioGeneral/DioReversePortBits"!]
        [!VAR "Reversed_offset"="DioPortMask"!]
        [!VAR "Reversed_mask"="0"!]
        [!VAR "Found_1"="0"!]
        [!FOR "Loop" = "0" TO "15"!]
            [!VAR "crt_bit" = "bit:shr($Orig_mask,$Loop)"!]
            [!VAR "crt_bit"="bit:and($crt_bit, 1)"!]
            [!VAR "Reversed_mask"="bit:or($Reversed_mask,$crt_bit)"!]
            [!IF "$Loop != 15"!][!//
                [!VAR "Reversed_mask"="bit:shl($Reversed_mask, 1)"!]
            [!ENDIF!]
            [!IF "$Found_1=1 and $crt_bit=0"!]
                [!VAR "right_bits"="$Loop"!]
                [!VAR "Found_1"="0"!]
            [!ENDIF!]
            [!IF "$crt_bit = 1"!]
                [!VAR "Found_1"="1"!]
            [!ENDIF!][!//
        [!ENDFOR!]
        [!VAR "Reversed_offset"="16-$right_bits"!]
    [!ELSE!]
        [!VAR "Reversed_offset"="DioPortOffset"!]
        [!VAR "Reversed_mask"="DioPortMask"!]
    [!ENDIF!]
[!ENDNOCODE!][!//
    (uint8)[!"num:inttohex($Reversed_offset,2)"!],
    (Dio_PortLevelType)[!"num:inttohex($Reversed_mask,4)"!]
[!ENDMACRO!][!//

/**
* @brief          Data structure for configuration Dio_ConfigPC
*/
/* @violates @ref Dio_CFG_REF_4 All declarations and definitions of objects or functions
at file scope shall have internal linkage unless external linkage is required */
CONST(Dio_ConfigType, DIO_CONST) Dio_ConfigPC = {(uint8)0};

[!LOOP "DioConfig/*"!][!//
[!LOOP "DioPort/*"!][!//
[!VAR "PortId" = "DioPortId"!][!//
[!VAR "PortName" = "concat('DioConf_DioPort_',node:name(.))"!][!//
[!//
[!LOOP "DioChannelGroup/*"!][!//
[!IF "DioChannelGroupIdentification != normalize-space(DioChannelGroupIdentification)"!][!//
[!ERROR "DioChannelGroupIdentification string should not start with space."!][!//
[!ENDIF!][!//
/**
* @brief          External declaration of channel group [!"DioChannelGroupIdentification"!].
*/
/*
* @violates @ref Dio_CFG_REF_4 All declarations and definitions of objects or
* functions at file scope shall have internal linkage unless external linkage is required
*/
CONST(Dio_ChannelGroupType, DIO_CONST) [!"DioChannelGroupIdentification"!] = {
    [!"$PortName"!],
[!CALL "reverse_bits"!][!//
};

[!ENDLOOP!][!//
[!ENDLOOP!][!//
[!ENDLOOP!][!//
/*
* @violates @ref Dio_CFG_REF_5 Identifiers (internal and external) shall not rely on the significance of more than 31
* characters.
*/
#define DIO_STOP_SEC_CONFIG_DATA_UNSPECIFIED
/* @violates @ref Dio_CFG_REF_1 only preprocessor statements and comments before '#include'.*/
/*
* @violates @ref Dio_CFG_REF_2 Precautions shall be taken in order to prevent
* the contents of a header file being included twice
*/
#include "MemMap.h"

/*==================================================================================================
*                                      GLOBAL VARIABLES
==================================================================================================*/


/*==================================================================================================
*                                   LOCAL FUNCTION PROTOTYPES
==================================================================================================*/


/*==================================================================================================
*                                       LOCAL FUNCTIONS
==================================================================================================*/


/*==================================================================================================
*                                       GLOBAL FUNCTIONS
==================================================================================================*/


#endif /* defined(DIO_PRECOMPILE_SUPPORT) */

#ifdef __cplusplus
}
#endif

/** @} */
[!ENDCODE!][!//
